//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Web.TenderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TenderServiceReference.TenderServiceSoap")]
    public interface TenderServiceSoap {
        
        // CODEGEN: Generating message contract since element name tenderTitle from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTender", ReplyAction="*")]
        SPC_Web.TenderServiceReference.AddTenderResponse AddTender(SPC_Web.TenderServiceReference.AddTenderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTender", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.AddTenderResponse> AddTenderAsync(SPC_Web.TenderServiceReference.AddTenderRequest request);
        
        // CODEGEN: Generating message contract since element name tenderTitle from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditTender", ReplyAction="*")]
        SPC_Web.TenderServiceReference.EditTenderResponse EditTender(SPC_Web.TenderServiceReference.EditTenderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditTender", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.EditTenderResponse> EditTenderAsync(SPC_Web.TenderServiceReference.EditTenderRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteTenderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTender", ReplyAction="*")]
        SPC_Web.TenderServiceReference.DeleteTenderResponse DeleteTender(SPC_Web.TenderServiceReference.DeleteTenderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTender", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.DeleteTenderResponse> DeleteTenderAsync(SPC_Web.TenderServiceReference.DeleteTenderRequest request);
        
        // CODEGEN: Generating message contract since element name newStatus from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeTenderStatus", ReplyAction="*")]
        SPC_Web.TenderServiceReference.ChangeTenderStatusResponse ChangeTenderStatus(SPC_Web.TenderServiceReference.ChangeTenderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeTenderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.ChangeTenderStatusResponse> ChangeTenderStatusAsync(SPC_Web.TenderServiceReference.ChangeTenderStatusRequest request);
        
        // CODEGEN: Generating message contract since element name ShowTendersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowTenders", ReplyAction="*")]
        SPC_Web.TenderServiceReference.ShowTendersResponse ShowTenders(SPC_Web.TenderServiceReference.ShowTendersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowTenders", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.ShowTendersResponse> ShowTendersAsync(SPC_Web.TenderServiceReference.ShowTendersRequest request);
        
        // CODEGEN: Generating message contract since element name supplierName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSupplier", ReplyAction="*")]
        SPC_Web.TenderServiceReference.AddSupplierResponse AddSupplier(SPC_Web.TenderServiceReference.AddSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.AddSupplierResponse> AddSupplierAsync(SPC_Web.TenderServiceReference.AddSupplierRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteSupplierResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSupplier", ReplyAction="*")]
        SPC_Web.TenderServiceReference.DeleteSupplierResponse DeleteSupplier(SPC_Web.TenderServiceReference.DeleteSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.DeleteSupplierResponse> DeleteSupplierAsync(SPC_Web.TenderServiceReference.DeleteSupplierRequest request);
        
        // CODEGEN: Generating message contract since element name ShowSuppliersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowSuppliers", ReplyAction="*")]
        SPC_Web.TenderServiceReference.ShowSuppliersResponse ShowSuppliers(SPC_Web.TenderServiceReference.ShowSuppliersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowSuppliers", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.ShowSuppliersResponse> ShowSuppliersAsync(SPC_Web.TenderServiceReference.ShowSuppliersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTender", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.AddTenderRequestBody Body;
        
        public AddTenderRequest() {
        }
        
        public AddTenderRequest(SPC_Web.TenderServiceReference.AddTenderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTenderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tenderTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int supplierId;
        
        public AddTenderRequestBody() {
        }
        
        public AddTenderRequestBody(string tenderTitle, string description, string status, int supplierId) {
            this.tenderTitle = tenderTitle;
            this.description = description;
            this.status = status;
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTenderResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.AddTenderResponseBody Body;
        
        public AddTenderResponse() {
        }
        
        public AddTenderResponse(SPC_Web.TenderServiceReference.AddTenderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTenderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddTenderResult;
        
        public AddTenderResponseBody() {
        }
        
        public AddTenderResponseBody(string AddTenderResult) {
            this.AddTenderResult = AddTenderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditTenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditTender", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.EditTenderRequestBody Body;
        
        public EditTenderRequest() {
        }
        
        public EditTenderRequest(SPC_Web.TenderServiceReference.EditTenderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditTenderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tenderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tenderTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int supplierId;
        
        public EditTenderRequestBody() {
        }
        
        public EditTenderRequestBody(int tenderId, string tenderTitle, string description, string status, int supplierId) {
            this.tenderId = tenderId;
            this.tenderTitle = tenderTitle;
            this.description = description;
            this.status = status;
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditTenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditTenderResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.EditTenderResponseBody Body;
        
        public EditTenderResponse() {
        }
        
        public EditTenderResponse(SPC_Web.TenderServiceReference.EditTenderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditTenderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditTenderResult;
        
        public EditTenderResponseBody() {
        }
        
        public EditTenderResponseBody(string EditTenderResult) {
            this.EditTenderResult = EditTenderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTender", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.DeleteTenderRequestBody Body;
        
        public DeleteTenderRequest() {
        }
        
        public DeleteTenderRequest(SPC_Web.TenderServiceReference.DeleteTenderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteTenderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tenderId;
        
        public DeleteTenderRequestBody() {
        }
        
        public DeleteTenderRequestBody(int tenderId) {
            this.tenderId = tenderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTenderResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.DeleteTenderResponseBody Body;
        
        public DeleteTenderResponse() {
        }
        
        public DeleteTenderResponse(SPC_Web.TenderServiceReference.DeleteTenderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteTenderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteTenderResult;
        
        public DeleteTenderResponseBody() {
        }
        
        public DeleteTenderResponseBody(string DeleteTenderResult) {
            this.DeleteTenderResult = DeleteTenderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeTenderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeTenderStatus", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.ChangeTenderStatusRequestBody Body;
        
        public ChangeTenderStatusRequest() {
        }
        
        public ChangeTenderStatusRequest(SPC_Web.TenderServiceReference.ChangeTenderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeTenderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tenderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newStatus;
        
        public ChangeTenderStatusRequestBody() {
        }
        
        public ChangeTenderStatusRequestBody(int tenderId, string newStatus) {
            this.tenderId = tenderId;
            this.newStatus = newStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeTenderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeTenderStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.ChangeTenderStatusResponseBody Body;
        
        public ChangeTenderStatusResponse() {
        }
        
        public ChangeTenderStatusResponse(SPC_Web.TenderServiceReference.ChangeTenderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeTenderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChangeTenderStatusResult;
        
        public ChangeTenderStatusResponseBody() {
        }
        
        public ChangeTenderStatusResponseBody(string ChangeTenderStatusResult) {
            this.ChangeTenderStatusResult = ChangeTenderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowTendersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowTenders", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.ShowTendersRequestBody Body;
        
        public ShowTendersRequest() {
        }
        
        public ShowTendersRequest(SPC_Web.TenderServiceReference.ShowTendersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowTendersRequestBody {
        
        public ShowTendersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowTendersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowTendersResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.ShowTendersResponseBody Body;
        
        public ShowTendersResponse() {
        }
        
        public ShowTendersResponse(SPC_Web.TenderServiceReference.ShowTendersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowTendersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowTendersResult;
        
        public ShowTendersResponseBody() {
        }
        
        public ShowTendersResponseBody(string ShowTendersResult) {
            this.ShowTendersResult = ShowTendersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSupplier", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.AddSupplierRequestBody Body;
        
        public AddSupplierRequest() {
        }
        
        public AddSupplierRequest(SPC_Web.TenderServiceReference.AddSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string supplierName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contactName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string status;
        
        public AddSupplierRequestBody() {
        }
        
        public AddSupplierRequestBody(string supplierName, string contactName, string address, string phoneNumber, string email, string status) {
            this.supplierName = supplierName;
            this.contactName = contactName;
            this.address = address;
            this.phoneNumber = phoneNumber;
            this.email = email;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.AddSupplierResponseBody Body;
        
        public AddSupplierResponse() {
        }
        
        public AddSupplierResponse(SPC_Web.TenderServiceReference.AddSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddSupplierResult;
        
        public AddSupplierResponseBody() {
        }
        
        public AddSupplierResponseBody(string AddSupplierResult) {
            this.AddSupplierResult = AddSupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSupplier", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.DeleteSupplierRequestBody Body;
        
        public DeleteSupplierRequest() {
        }
        
        public DeleteSupplierRequest(SPC_Web.TenderServiceReference.DeleteSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplierId;
        
        public DeleteSupplierRequestBody() {
        }
        
        public DeleteSupplierRequestBody(int supplierId) {
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.DeleteSupplierResponseBody Body;
        
        public DeleteSupplierResponse() {
        }
        
        public DeleteSupplierResponse(SPC_Web.TenderServiceReference.DeleteSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteSupplierResult;
        
        public DeleteSupplierResponseBody() {
        }
        
        public DeleteSupplierResponseBody(string DeleteSupplierResult) {
            this.DeleteSupplierResult = DeleteSupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowSuppliersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowSuppliers", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.ShowSuppliersRequestBody Body;
        
        public ShowSuppliersRequest() {
        }
        
        public ShowSuppliersRequest(SPC_Web.TenderServiceReference.ShowSuppliersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowSuppliersRequestBody {
        
        public ShowSuppliersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowSuppliersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowSuppliersResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.TenderServiceReference.ShowSuppliersResponseBody Body;
        
        public ShowSuppliersResponse() {
        }
        
        public ShowSuppliersResponse(SPC_Web.TenderServiceReference.ShowSuppliersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowSuppliersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowSuppliersResult;
        
        public ShowSuppliersResponseBody() {
        }
        
        public ShowSuppliersResponseBody(string ShowSuppliersResult) {
            this.ShowSuppliersResult = ShowSuppliersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TenderServiceSoapChannel : SPC_Web.TenderServiceReference.TenderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TenderServiceSoapClient : System.ServiceModel.ClientBase<SPC_Web.TenderServiceReference.TenderServiceSoap>, SPC_Web.TenderServiceReference.TenderServiceSoap {
        
        public TenderServiceSoapClient() {
        }
        
        public TenderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TenderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TenderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TenderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.TenderServiceReference.AddTenderResponse SPC_Web.TenderServiceReference.TenderServiceSoap.AddTender(SPC_Web.TenderServiceReference.AddTenderRequest request) {
            return base.Channel.AddTender(request);
        }
        
        public string AddTender(string tenderTitle, string description, string status, int supplierId) {
            SPC_Web.TenderServiceReference.AddTenderRequest inValue = new SPC_Web.TenderServiceReference.AddTenderRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.AddTenderRequestBody();
            inValue.Body.tenderTitle = tenderTitle;
            inValue.Body.description = description;
            inValue.Body.status = status;
            inValue.Body.supplierId = supplierId;
            SPC_Web.TenderServiceReference.AddTenderResponse retVal = ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).AddTender(inValue);
            return retVal.Body.AddTenderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.AddTenderResponse> SPC_Web.TenderServiceReference.TenderServiceSoap.AddTenderAsync(SPC_Web.TenderServiceReference.AddTenderRequest request) {
            return base.Channel.AddTenderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.AddTenderResponse> AddTenderAsync(string tenderTitle, string description, string status, int supplierId) {
            SPC_Web.TenderServiceReference.AddTenderRequest inValue = new SPC_Web.TenderServiceReference.AddTenderRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.AddTenderRequestBody();
            inValue.Body.tenderTitle = tenderTitle;
            inValue.Body.description = description;
            inValue.Body.status = status;
            inValue.Body.supplierId = supplierId;
            return ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).AddTenderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.TenderServiceReference.EditTenderResponse SPC_Web.TenderServiceReference.TenderServiceSoap.EditTender(SPC_Web.TenderServiceReference.EditTenderRequest request) {
            return base.Channel.EditTender(request);
        }
        
        public string EditTender(int tenderId, string tenderTitle, string description, string status, int supplierId) {
            SPC_Web.TenderServiceReference.EditTenderRequest inValue = new SPC_Web.TenderServiceReference.EditTenderRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.EditTenderRequestBody();
            inValue.Body.tenderId = tenderId;
            inValue.Body.tenderTitle = tenderTitle;
            inValue.Body.description = description;
            inValue.Body.status = status;
            inValue.Body.supplierId = supplierId;
            SPC_Web.TenderServiceReference.EditTenderResponse retVal = ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).EditTender(inValue);
            return retVal.Body.EditTenderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.EditTenderResponse> SPC_Web.TenderServiceReference.TenderServiceSoap.EditTenderAsync(SPC_Web.TenderServiceReference.EditTenderRequest request) {
            return base.Channel.EditTenderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.EditTenderResponse> EditTenderAsync(int tenderId, string tenderTitle, string description, string status, int supplierId) {
            SPC_Web.TenderServiceReference.EditTenderRequest inValue = new SPC_Web.TenderServiceReference.EditTenderRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.EditTenderRequestBody();
            inValue.Body.tenderId = tenderId;
            inValue.Body.tenderTitle = tenderTitle;
            inValue.Body.description = description;
            inValue.Body.status = status;
            inValue.Body.supplierId = supplierId;
            return ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).EditTenderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.TenderServiceReference.DeleteTenderResponse SPC_Web.TenderServiceReference.TenderServiceSoap.DeleteTender(SPC_Web.TenderServiceReference.DeleteTenderRequest request) {
            return base.Channel.DeleteTender(request);
        }
        
        public string DeleteTender(int tenderId) {
            SPC_Web.TenderServiceReference.DeleteTenderRequest inValue = new SPC_Web.TenderServiceReference.DeleteTenderRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.DeleteTenderRequestBody();
            inValue.Body.tenderId = tenderId;
            SPC_Web.TenderServiceReference.DeleteTenderResponse retVal = ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).DeleteTender(inValue);
            return retVal.Body.DeleteTenderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.DeleteTenderResponse> SPC_Web.TenderServiceReference.TenderServiceSoap.DeleteTenderAsync(SPC_Web.TenderServiceReference.DeleteTenderRequest request) {
            return base.Channel.DeleteTenderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.DeleteTenderResponse> DeleteTenderAsync(int tenderId) {
            SPC_Web.TenderServiceReference.DeleteTenderRequest inValue = new SPC_Web.TenderServiceReference.DeleteTenderRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.DeleteTenderRequestBody();
            inValue.Body.tenderId = tenderId;
            return ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).DeleteTenderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.TenderServiceReference.ChangeTenderStatusResponse SPC_Web.TenderServiceReference.TenderServiceSoap.ChangeTenderStatus(SPC_Web.TenderServiceReference.ChangeTenderStatusRequest request) {
            return base.Channel.ChangeTenderStatus(request);
        }
        
        public string ChangeTenderStatus(int tenderId, string newStatus) {
            SPC_Web.TenderServiceReference.ChangeTenderStatusRequest inValue = new SPC_Web.TenderServiceReference.ChangeTenderStatusRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.ChangeTenderStatusRequestBody();
            inValue.Body.tenderId = tenderId;
            inValue.Body.newStatus = newStatus;
            SPC_Web.TenderServiceReference.ChangeTenderStatusResponse retVal = ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).ChangeTenderStatus(inValue);
            return retVal.Body.ChangeTenderStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.ChangeTenderStatusResponse> SPC_Web.TenderServiceReference.TenderServiceSoap.ChangeTenderStatusAsync(SPC_Web.TenderServiceReference.ChangeTenderStatusRequest request) {
            return base.Channel.ChangeTenderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.ChangeTenderStatusResponse> ChangeTenderStatusAsync(int tenderId, string newStatus) {
            SPC_Web.TenderServiceReference.ChangeTenderStatusRequest inValue = new SPC_Web.TenderServiceReference.ChangeTenderStatusRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.ChangeTenderStatusRequestBody();
            inValue.Body.tenderId = tenderId;
            inValue.Body.newStatus = newStatus;
            return ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).ChangeTenderStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.TenderServiceReference.ShowTendersResponse SPC_Web.TenderServiceReference.TenderServiceSoap.ShowTenders(SPC_Web.TenderServiceReference.ShowTendersRequest request) {
            return base.Channel.ShowTenders(request);
        }
        
        public string ShowTenders() {
            SPC_Web.TenderServiceReference.ShowTendersRequest inValue = new SPC_Web.TenderServiceReference.ShowTendersRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.ShowTendersRequestBody();
            SPC_Web.TenderServiceReference.ShowTendersResponse retVal = ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).ShowTenders(inValue);
            return retVal.Body.ShowTendersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.ShowTendersResponse> SPC_Web.TenderServiceReference.TenderServiceSoap.ShowTendersAsync(SPC_Web.TenderServiceReference.ShowTendersRequest request) {
            return base.Channel.ShowTendersAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.ShowTendersResponse> ShowTendersAsync() {
            SPC_Web.TenderServiceReference.ShowTendersRequest inValue = new SPC_Web.TenderServiceReference.ShowTendersRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.ShowTendersRequestBody();
            return ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).ShowTendersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.TenderServiceReference.AddSupplierResponse SPC_Web.TenderServiceReference.TenderServiceSoap.AddSupplier(SPC_Web.TenderServiceReference.AddSupplierRequest request) {
            return base.Channel.AddSupplier(request);
        }
        
        public string AddSupplier(string supplierName, string contactName, string address, string phoneNumber, string email, string status) {
            SPC_Web.TenderServiceReference.AddSupplierRequest inValue = new SPC_Web.TenderServiceReference.AddSupplierRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.AddSupplierRequestBody();
            inValue.Body.supplierName = supplierName;
            inValue.Body.contactName = contactName;
            inValue.Body.address = address;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            inValue.Body.status = status;
            SPC_Web.TenderServiceReference.AddSupplierResponse retVal = ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).AddSupplier(inValue);
            return retVal.Body.AddSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.AddSupplierResponse> SPC_Web.TenderServiceReference.TenderServiceSoap.AddSupplierAsync(SPC_Web.TenderServiceReference.AddSupplierRequest request) {
            return base.Channel.AddSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.AddSupplierResponse> AddSupplierAsync(string supplierName, string contactName, string address, string phoneNumber, string email, string status) {
            SPC_Web.TenderServiceReference.AddSupplierRequest inValue = new SPC_Web.TenderServiceReference.AddSupplierRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.AddSupplierRequestBody();
            inValue.Body.supplierName = supplierName;
            inValue.Body.contactName = contactName;
            inValue.Body.address = address;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            inValue.Body.status = status;
            return ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).AddSupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.TenderServiceReference.DeleteSupplierResponse SPC_Web.TenderServiceReference.TenderServiceSoap.DeleteSupplier(SPC_Web.TenderServiceReference.DeleteSupplierRequest request) {
            return base.Channel.DeleteSupplier(request);
        }
        
        public string DeleteSupplier(int supplierId) {
            SPC_Web.TenderServiceReference.DeleteSupplierRequest inValue = new SPC_Web.TenderServiceReference.DeleteSupplierRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.DeleteSupplierRequestBody();
            inValue.Body.supplierId = supplierId;
            SPC_Web.TenderServiceReference.DeleteSupplierResponse retVal = ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).DeleteSupplier(inValue);
            return retVal.Body.DeleteSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.DeleteSupplierResponse> SPC_Web.TenderServiceReference.TenderServiceSoap.DeleteSupplierAsync(SPC_Web.TenderServiceReference.DeleteSupplierRequest request) {
            return base.Channel.DeleteSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.DeleteSupplierResponse> DeleteSupplierAsync(int supplierId) {
            SPC_Web.TenderServiceReference.DeleteSupplierRequest inValue = new SPC_Web.TenderServiceReference.DeleteSupplierRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.DeleteSupplierRequestBody();
            inValue.Body.supplierId = supplierId;
            return ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).DeleteSupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.TenderServiceReference.ShowSuppliersResponse SPC_Web.TenderServiceReference.TenderServiceSoap.ShowSuppliers(SPC_Web.TenderServiceReference.ShowSuppliersRequest request) {
            return base.Channel.ShowSuppliers(request);
        }
        
        public string ShowSuppliers() {
            SPC_Web.TenderServiceReference.ShowSuppliersRequest inValue = new SPC_Web.TenderServiceReference.ShowSuppliersRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.ShowSuppliersRequestBody();
            SPC_Web.TenderServiceReference.ShowSuppliersResponse retVal = ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).ShowSuppliers(inValue);
            return retVal.Body.ShowSuppliersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.ShowSuppliersResponse> SPC_Web.TenderServiceReference.TenderServiceSoap.ShowSuppliersAsync(SPC_Web.TenderServiceReference.ShowSuppliersRequest request) {
            return base.Channel.ShowSuppliersAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.TenderServiceReference.ShowSuppliersResponse> ShowSuppliersAsync() {
            SPC_Web.TenderServiceReference.ShowSuppliersRequest inValue = new SPC_Web.TenderServiceReference.ShowSuppliersRequest();
            inValue.Body = new SPC_Web.TenderServiceReference.ShowSuppliersRequestBody();
            return ((SPC_Web.TenderServiceReference.TenderServiceSoap)(this)).ShowSuppliersAsync(inValue);
        }
    }
}
