//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Web.RegisterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegisterServiceReference.RegisterServiceSoap")]
    public interface RegisterServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        SPC_Web.RegisterServiceReference.RegisterUserResponse RegisterUser(SPC_Web.RegisterServiceReference.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.RegisterServiceReference.RegisterUserResponse> RegisterUserAsync(SPC_Web.RegisterServiceReference.RegisterUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUser", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.RegisterServiceReference.RegisterUserRequestBody Body;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(SPC_Web.RegisterServiceReference.RegisterUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string passwordHash;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int roleId;
        
        public RegisterUserRequestBody() {
        }
        
        public RegisterUserRequestBody(string userName, string email, string passwordHash, int roleId) {
            this.userName = userName;
            this.email = email;
            this.passwordHash = passwordHash;
            this.roleId = roleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.RegisterServiceReference.RegisterUserResponseBody Body;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(SPC_Web.RegisterServiceReference.RegisterUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterUserResult;
        
        public RegisterUserResponseBody() {
        }
        
        public RegisterUserResponseBody(string RegisterUserResult) {
            this.RegisterUserResult = RegisterUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegisterServiceSoapChannel : SPC_Web.RegisterServiceReference.RegisterServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterServiceSoapClient : System.ServiceModel.ClientBase<SPC_Web.RegisterServiceReference.RegisterServiceSoap>, SPC_Web.RegisterServiceReference.RegisterServiceSoap {
        
        public RegisterServiceSoapClient() {
        }
        
        public RegisterServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.RegisterServiceReference.RegisterUserResponse SPC_Web.RegisterServiceReference.RegisterServiceSoap.RegisterUser(SPC_Web.RegisterServiceReference.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public string RegisterUser(string userName, string email, string passwordHash, int roleId) {
            SPC_Web.RegisterServiceReference.RegisterUserRequest inValue = new SPC_Web.RegisterServiceReference.RegisterUserRequest();
            inValue.Body = new SPC_Web.RegisterServiceReference.RegisterUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.email = email;
            inValue.Body.passwordHash = passwordHash;
            inValue.Body.roleId = roleId;
            SPC_Web.RegisterServiceReference.RegisterUserResponse retVal = ((SPC_Web.RegisterServiceReference.RegisterServiceSoap)(this)).RegisterUser(inValue);
            return retVal.Body.RegisterUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.RegisterServiceReference.RegisterUserResponse> SPC_Web.RegisterServiceReference.RegisterServiceSoap.RegisterUserAsync(SPC_Web.RegisterServiceReference.RegisterUserRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.RegisterServiceReference.RegisterUserResponse> RegisterUserAsync(string userName, string email, string passwordHash, int roleId) {
            SPC_Web.RegisterServiceReference.RegisterUserRequest inValue = new SPC_Web.RegisterServiceReference.RegisterUserRequest();
            inValue.Body = new SPC_Web.RegisterServiceReference.RegisterUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.email = email;
            inValue.Body.passwordHash = passwordHash;
            inValue.Body.roleId = roleId;
            return ((SPC_Web.RegisterServiceReference.RegisterServiceSoap)(this)).RegisterUserAsync(inValue);
        }
    }
}
