//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Web.InventoryServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventoryItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class InventoryItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int InventoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrugNameField;
        
        private int QuantityField;
        
        private System.DateTime ExpiryDateField;
        
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockStatusField;
        
        private int SupplierIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int InventoryId {
            get {
                return this.InventoryIdField;
            }
            set {
                if ((this.InventoryIdField.Equals(value) != true)) {
                    this.InventoryIdField = value;
                    this.RaisePropertyChanged("InventoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DrugName {
            get {
                return this.DrugNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DrugNameField, value) != true)) {
                    this.DrugNameField = value;
                    this.RaisePropertyChanged("DrugName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((this.ExpiryDateField.Equals(value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StockStatus {
            get {
                return this.StockStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StockStatusField, value) != true)) {
                    this.StockStatusField = value;
                    this.RaisePropertyChanged("StockStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InventoryServiceReference.InventoryServiceSoap")]
    public interface InventoryServiceSoap {
        
        // CODEGEN: Generating message contract since element name drugName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddInventory", ReplyAction="*")]
        SPC_Web.InventoryServiceReference.AddInventoryResponse AddInventory(SPC_Web.InventoryServiceReference.AddInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.AddInventoryResponse> AddInventoryAsync(SPC_Web.InventoryServiceReference.AddInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name drugName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditInventory", ReplyAction="*")]
        SPC_Web.InventoryServiceReference.EditInventoryResponse EditInventory(SPC_Web.InventoryServiceReference.EditInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.EditInventoryResponse> EditInventoryAsync(SPC_Web.InventoryServiceReference.EditInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteInventoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteInventory", ReplyAction="*")]
        SPC_Web.InventoryServiceReference.DeleteInventoryResponse DeleteInventory(SPC_Web.InventoryServiceReference.DeleteInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.DeleteInventoryResponse> DeleteInventoryAsync(SPC_Web.InventoryServiceReference.DeleteInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetInventoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInventory", ReplyAction="*")]
        SPC_Web.InventoryServiceReference.GetInventoryResponse GetInventory(SPC_Web.InventoryServiceReference.GetInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.GetInventoryResponse> GetInventoryAsync(SPC_Web.InventoryServiceReference.GetInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name searchTerm from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchInventory", ReplyAction="*")]
        SPC_Web.InventoryServiceReference.SearchInventoryResponse SearchInventory(SPC_Web.InventoryServiceReference.SearchInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.SearchInventoryResponse> SearchInventoryAsync(SPC_Web.InventoryServiceReference.SearchInventoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddInventory", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.InventoryServiceReference.AddInventoryRequestBody Body;
        
        public AddInventoryRequest() {
        }
        
        public AddInventoryRequest(SPC_Web.InventoryServiceReference.AddInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string drugName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime expiryDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string stockStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int supplierId;
        
        public AddInventoryRequestBody() {
        }
        
        public AddInventoryRequestBody(string drugName, int quantity, System.DateTime expiryDate, decimal price, string stockStatus, int supplierId) {
            this.drugName = drugName;
            this.quantity = quantity;
            this.expiryDate = expiryDate;
            this.price = price;
            this.stockStatus = stockStatus;
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.InventoryServiceReference.AddInventoryResponseBody Body;
        
        public AddInventoryResponse() {
        }
        
        public AddInventoryResponse(SPC_Web.InventoryServiceReference.AddInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddInventoryResult;
        
        public AddInventoryResponseBody() {
        }
        
        public AddInventoryResponseBody(string AddInventoryResult) {
            this.AddInventoryResult = AddInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditInventory", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.InventoryServiceReference.EditInventoryRequestBody Body;
        
        public EditInventoryRequest() {
        }
        
        public EditInventoryRequest(SPC_Web.InventoryServiceReference.EditInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int inventoryId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string drugName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime expiryDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string stockStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int supplierId;
        
        public EditInventoryRequestBody() {
        }
        
        public EditInventoryRequestBody(int inventoryId, string drugName, int quantity, System.DateTime expiryDate, decimal price, string stockStatus, int supplierId) {
            this.inventoryId = inventoryId;
            this.drugName = drugName;
            this.quantity = quantity;
            this.expiryDate = expiryDate;
            this.price = price;
            this.stockStatus = stockStatus;
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.InventoryServiceReference.EditInventoryResponseBody Body;
        
        public EditInventoryResponse() {
        }
        
        public EditInventoryResponse(SPC_Web.InventoryServiceReference.EditInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditInventoryResult;
        
        public EditInventoryResponseBody() {
        }
        
        public EditInventoryResponseBody(string EditInventoryResult) {
            this.EditInventoryResult = EditInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteInventory", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.InventoryServiceReference.DeleteInventoryRequestBody Body;
        
        public DeleteInventoryRequest() {
        }
        
        public DeleteInventoryRequest(SPC_Web.InventoryServiceReference.DeleteInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int inventoryId;
        
        public DeleteInventoryRequestBody() {
        }
        
        public DeleteInventoryRequestBody(int inventoryId) {
            this.inventoryId = inventoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.InventoryServiceReference.DeleteInventoryResponseBody Body;
        
        public DeleteInventoryResponse() {
        }
        
        public DeleteInventoryResponse(SPC_Web.InventoryServiceReference.DeleteInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteInventoryResult;
        
        public DeleteInventoryResponseBody() {
        }
        
        public DeleteInventoryResponseBody(string DeleteInventoryResult) {
            this.DeleteInventoryResult = DeleteInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInventory", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.InventoryServiceReference.GetInventoryRequestBody Body;
        
        public GetInventoryRequest() {
        }
        
        public GetInventoryRequest(SPC_Web.InventoryServiceReference.GetInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInventoryRequestBody {
        
        public GetInventoryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.InventoryServiceReference.GetInventoryResponseBody Body;
        
        public GetInventoryResponse() {
        }
        
        public GetInventoryResponse(SPC_Web.InventoryServiceReference.GetInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SPC_Web.InventoryServiceReference.InventoryItem[] GetInventoryResult;
        
        public GetInventoryResponseBody() {
        }
        
        public GetInventoryResponseBody(SPC_Web.InventoryServiceReference.InventoryItem[] GetInventoryResult) {
            this.GetInventoryResult = GetInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchInventory", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.InventoryServiceReference.SearchInventoryRequestBody Body;
        
        public SearchInventoryRequest() {
        }
        
        public SearchInventoryRequest(SPC_Web.InventoryServiceReference.SearchInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchTerm;
        
        public SearchInventoryRequestBody() {
        }
        
        public SearchInventoryRequestBody(string searchTerm) {
            this.searchTerm = searchTerm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.InventoryServiceReference.SearchInventoryResponseBody Body;
        
        public SearchInventoryResponse() {
        }
        
        public SearchInventoryResponse(SPC_Web.InventoryServiceReference.SearchInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SPC_Web.InventoryServiceReference.InventoryItem[] SearchInventoryResult;
        
        public SearchInventoryResponseBody() {
        }
        
        public SearchInventoryResponseBody(SPC_Web.InventoryServiceReference.InventoryItem[] SearchInventoryResult) {
            this.SearchInventoryResult = SearchInventoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InventoryServiceSoapChannel : SPC_Web.InventoryServiceReference.InventoryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventoryServiceSoapClient : System.ServiceModel.ClientBase<SPC_Web.InventoryServiceReference.InventoryServiceSoap>, SPC_Web.InventoryServiceReference.InventoryServiceSoap {
        
        public InventoryServiceSoapClient() {
        }
        
        public InventoryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventoryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.InventoryServiceReference.AddInventoryResponse SPC_Web.InventoryServiceReference.InventoryServiceSoap.AddInventory(SPC_Web.InventoryServiceReference.AddInventoryRequest request) {
            return base.Channel.AddInventory(request);
        }
        
        public string AddInventory(string drugName, int quantity, System.DateTime expiryDate, decimal price, string stockStatus, int supplierId) {
            SPC_Web.InventoryServiceReference.AddInventoryRequest inValue = new SPC_Web.InventoryServiceReference.AddInventoryRequest();
            inValue.Body = new SPC_Web.InventoryServiceReference.AddInventoryRequestBody();
            inValue.Body.drugName = drugName;
            inValue.Body.quantity = quantity;
            inValue.Body.expiryDate = expiryDate;
            inValue.Body.price = price;
            inValue.Body.stockStatus = stockStatus;
            inValue.Body.supplierId = supplierId;
            SPC_Web.InventoryServiceReference.AddInventoryResponse retVal = ((SPC_Web.InventoryServiceReference.InventoryServiceSoap)(this)).AddInventory(inValue);
            return retVal.Body.AddInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.AddInventoryResponse> SPC_Web.InventoryServiceReference.InventoryServiceSoap.AddInventoryAsync(SPC_Web.InventoryServiceReference.AddInventoryRequest request) {
            return base.Channel.AddInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.AddInventoryResponse> AddInventoryAsync(string drugName, int quantity, System.DateTime expiryDate, decimal price, string stockStatus, int supplierId) {
            SPC_Web.InventoryServiceReference.AddInventoryRequest inValue = new SPC_Web.InventoryServiceReference.AddInventoryRequest();
            inValue.Body = new SPC_Web.InventoryServiceReference.AddInventoryRequestBody();
            inValue.Body.drugName = drugName;
            inValue.Body.quantity = quantity;
            inValue.Body.expiryDate = expiryDate;
            inValue.Body.price = price;
            inValue.Body.stockStatus = stockStatus;
            inValue.Body.supplierId = supplierId;
            return ((SPC_Web.InventoryServiceReference.InventoryServiceSoap)(this)).AddInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.InventoryServiceReference.EditInventoryResponse SPC_Web.InventoryServiceReference.InventoryServiceSoap.EditInventory(SPC_Web.InventoryServiceReference.EditInventoryRequest request) {
            return base.Channel.EditInventory(request);
        }
        
        public string EditInventory(int inventoryId, string drugName, int quantity, System.DateTime expiryDate, decimal price, string stockStatus, int supplierId) {
            SPC_Web.InventoryServiceReference.EditInventoryRequest inValue = new SPC_Web.InventoryServiceReference.EditInventoryRequest();
            inValue.Body = new SPC_Web.InventoryServiceReference.EditInventoryRequestBody();
            inValue.Body.inventoryId = inventoryId;
            inValue.Body.drugName = drugName;
            inValue.Body.quantity = quantity;
            inValue.Body.expiryDate = expiryDate;
            inValue.Body.price = price;
            inValue.Body.stockStatus = stockStatus;
            inValue.Body.supplierId = supplierId;
            SPC_Web.InventoryServiceReference.EditInventoryResponse retVal = ((SPC_Web.InventoryServiceReference.InventoryServiceSoap)(this)).EditInventory(inValue);
            return retVal.Body.EditInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.EditInventoryResponse> SPC_Web.InventoryServiceReference.InventoryServiceSoap.EditInventoryAsync(SPC_Web.InventoryServiceReference.EditInventoryRequest request) {
            return base.Channel.EditInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.EditInventoryResponse> EditInventoryAsync(int inventoryId, string drugName, int quantity, System.DateTime expiryDate, decimal price, string stockStatus, int supplierId) {
            SPC_Web.InventoryServiceReference.EditInventoryRequest inValue = new SPC_Web.InventoryServiceReference.EditInventoryRequest();
            inValue.Body = new SPC_Web.InventoryServiceReference.EditInventoryRequestBody();
            inValue.Body.inventoryId = inventoryId;
            inValue.Body.drugName = drugName;
            inValue.Body.quantity = quantity;
            inValue.Body.expiryDate = expiryDate;
            inValue.Body.price = price;
            inValue.Body.stockStatus = stockStatus;
            inValue.Body.supplierId = supplierId;
            return ((SPC_Web.InventoryServiceReference.InventoryServiceSoap)(this)).EditInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.InventoryServiceReference.DeleteInventoryResponse SPC_Web.InventoryServiceReference.InventoryServiceSoap.DeleteInventory(SPC_Web.InventoryServiceReference.DeleteInventoryRequest request) {
            return base.Channel.DeleteInventory(request);
        }
        
        public string DeleteInventory(int inventoryId) {
            SPC_Web.InventoryServiceReference.DeleteInventoryRequest inValue = new SPC_Web.InventoryServiceReference.DeleteInventoryRequest();
            inValue.Body = new SPC_Web.InventoryServiceReference.DeleteInventoryRequestBody();
            inValue.Body.inventoryId = inventoryId;
            SPC_Web.InventoryServiceReference.DeleteInventoryResponse retVal = ((SPC_Web.InventoryServiceReference.InventoryServiceSoap)(this)).DeleteInventory(inValue);
            return retVal.Body.DeleteInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.DeleteInventoryResponse> SPC_Web.InventoryServiceReference.InventoryServiceSoap.DeleteInventoryAsync(SPC_Web.InventoryServiceReference.DeleteInventoryRequest request) {
            return base.Channel.DeleteInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.DeleteInventoryResponse> DeleteInventoryAsync(int inventoryId) {
            SPC_Web.InventoryServiceReference.DeleteInventoryRequest inValue = new SPC_Web.InventoryServiceReference.DeleteInventoryRequest();
            inValue.Body = new SPC_Web.InventoryServiceReference.DeleteInventoryRequestBody();
            inValue.Body.inventoryId = inventoryId;
            return ((SPC_Web.InventoryServiceReference.InventoryServiceSoap)(this)).DeleteInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.InventoryServiceReference.GetInventoryResponse SPC_Web.InventoryServiceReference.InventoryServiceSoap.GetInventory(SPC_Web.InventoryServiceReference.GetInventoryRequest request) {
            return base.Channel.GetInventory(request);
        }
        
        public SPC_Web.InventoryServiceReference.InventoryItem[] GetInventory() {
            SPC_Web.InventoryServiceReference.GetInventoryRequest inValue = new SPC_Web.InventoryServiceReference.GetInventoryRequest();
            inValue.Body = new SPC_Web.InventoryServiceReference.GetInventoryRequestBody();
            SPC_Web.InventoryServiceReference.GetInventoryResponse retVal = ((SPC_Web.InventoryServiceReference.InventoryServiceSoap)(this)).GetInventory(inValue);
            return retVal.Body.GetInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.GetInventoryResponse> SPC_Web.InventoryServiceReference.InventoryServiceSoap.GetInventoryAsync(SPC_Web.InventoryServiceReference.GetInventoryRequest request) {
            return base.Channel.GetInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.GetInventoryResponse> GetInventoryAsync() {
            SPC_Web.InventoryServiceReference.GetInventoryRequest inValue = new SPC_Web.InventoryServiceReference.GetInventoryRequest();
            inValue.Body = new SPC_Web.InventoryServiceReference.GetInventoryRequestBody();
            return ((SPC_Web.InventoryServiceReference.InventoryServiceSoap)(this)).GetInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.InventoryServiceReference.SearchInventoryResponse SPC_Web.InventoryServiceReference.InventoryServiceSoap.SearchInventory(SPC_Web.InventoryServiceReference.SearchInventoryRequest request) {
            return base.Channel.SearchInventory(request);
        }
        
        public SPC_Web.InventoryServiceReference.InventoryItem[] SearchInventory(string searchTerm) {
            SPC_Web.InventoryServiceReference.SearchInventoryRequest inValue = new SPC_Web.InventoryServiceReference.SearchInventoryRequest();
            inValue.Body = new SPC_Web.InventoryServiceReference.SearchInventoryRequestBody();
            inValue.Body.searchTerm = searchTerm;
            SPC_Web.InventoryServiceReference.SearchInventoryResponse retVal = ((SPC_Web.InventoryServiceReference.InventoryServiceSoap)(this)).SearchInventory(inValue);
            return retVal.Body.SearchInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.SearchInventoryResponse> SPC_Web.InventoryServiceReference.InventoryServiceSoap.SearchInventoryAsync(SPC_Web.InventoryServiceReference.SearchInventoryRequest request) {
            return base.Channel.SearchInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.InventoryServiceReference.SearchInventoryResponse> SearchInventoryAsync(string searchTerm) {
            SPC_Web.InventoryServiceReference.SearchInventoryRequest inValue = new SPC_Web.InventoryServiceReference.SearchInventoryRequest();
            inValue.Body = new SPC_Web.InventoryServiceReference.SearchInventoryRequestBody();
            inValue.Body.searchTerm = searchTerm;
            return ((SPC_Web.InventoryServiceReference.InventoryServiceSoap)(this)).SearchInventoryAsync(inValue);
        }
    }
}
