//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Web.LogoutServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogoutServiceReference.LogoutServiceSoap")]
    public interface LogoutServiceSoap {
        
        // CODEGEN: Generating message contract since element name LogoutResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        SPC_Web.LogoutServiceReference.LogoutResponse Logout(SPC_Web.LogoutServiceReference.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.LogoutServiceReference.LogoutResponse> LogoutAsync(SPC_Web.LogoutServiceReference.LogoutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.LogoutServiceReference.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(SPC_Web.LogoutServiceReference.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogoutRequestBody {
        
        public LogoutRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.LogoutServiceReference.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(SPC_Web.LogoutServiceReference.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogoutResult;
        
        public LogoutResponseBody() {
        }
        
        public LogoutResponseBody(string LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogoutServiceSoapChannel : SPC_Web.LogoutServiceReference.LogoutServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogoutServiceSoapClient : System.ServiceModel.ClientBase<SPC_Web.LogoutServiceReference.LogoutServiceSoap>, SPC_Web.LogoutServiceReference.LogoutServiceSoap {
        
        public LogoutServiceSoapClient() {
        }
        
        public LogoutServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogoutServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogoutServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogoutServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.LogoutServiceReference.LogoutResponse SPC_Web.LogoutServiceReference.LogoutServiceSoap.Logout(SPC_Web.LogoutServiceReference.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public string Logout() {
            SPC_Web.LogoutServiceReference.LogoutRequest inValue = new SPC_Web.LogoutServiceReference.LogoutRequest();
            inValue.Body = new SPC_Web.LogoutServiceReference.LogoutRequestBody();
            SPC_Web.LogoutServiceReference.LogoutResponse retVal = ((SPC_Web.LogoutServiceReference.LogoutServiceSoap)(this)).Logout(inValue);
            return retVal.Body.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.LogoutServiceReference.LogoutResponse> SPC_Web.LogoutServiceReference.LogoutServiceSoap.LogoutAsync(SPC_Web.LogoutServiceReference.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.LogoutServiceReference.LogoutResponse> LogoutAsync() {
            SPC_Web.LogoutServiceReference.LogoutRequest inValue = new SPC_Web.LogoutServiceReference.LogoutRequest();
            inValue.Body = new SPC_Web.LogoutServiceReference.LogoutRequestBody();
            return ((SPC_Web.LogoutServiceReference.LogoutServiceSoap)(this)).LogoutAsync(inValue);
        }
    }
}
