//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Web.SupplierServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupplierServiceReference.SupplierServiceSoap")]
    public interface SupplierServiceSoap {
        
        // CODEGEN: Generating message contract since element name supplierName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterSupplier", ReplyAction="*")]
        SPC_Web.SupplierServiceReference.RegisterSupplierResponse RegisterSupplier(SPC_Web.SupplierServiceReference.RegisterSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.SupplierServiceReference.RegisterSupplierResponse> RegisterSupplierAsync(SPC_Web.SupplierServiceReference.RegisterSupplierRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SupplierLogin", ReplyAction="*")]
        SPC_Web.SupplierServiceReference.SupplierLoginResponse SupplierLogin(SPC_Web.SupplierServiceReference.SupplierLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SupplierLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.SupplierServiceReference.SupplierLoginResponse> SupplierLoginAsync(SPC_Web.SupplierServiceReference.SupplierLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterSupplier", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.SupplierServiceReference.RegisterSupplierRequestBody Body;
        
        public RegisterSupplierRequest() {
        }
        
        public RegisterSupplierRequest(SPC_Web.SupplierServiceReference.RegisterSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string supplierName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contactName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email;
        
        public RegisterSupplierRequestBody() {
        }
        
        public RegisterSupplierRequestBody(string supplierName, string contactName, string address, string phoneNumber, string email) {
            this.supplierName = supplierName;
            this.contactName = contactName;
            this.address = address;
            this.phoneNumber = phoneNumber;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.SupplierServiceReference.RegisterSupplierResponseBody Body;
        
        public RegisterSupplierResponse() {
        }
        
        public RegisterSupplierResponse(SPC_Web.SupplierServiceReference.RegisterSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterSupplierResult;
        
        public RegisterSupplierResponseBody() {
        }
        
        public RegisterSupplierResponseBody(string RegisterSupplierResult) {
            this.RegisterSupplierResult = RegisterSupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SupplierLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SupplierLogin", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.SupplierServiceReference.SupplierLoginRequestBody Body;
        
        public SupplierLoginRequest() {
        }
        
        public SupplierLoginRequest(SPC_Web.SupplierServiceReference.SupplierLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SupplierLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public SupplierLoginRequestBody() {
        }
        
        public SupplierLoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SupplierLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SupplierLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.SupplierServiceReference.SupplierLoginResponseBody Body;
        
        public SupplierLoginResponse() {
        }
        
        public SupplierLoginResponse(SPC_Web.SupplierServiceReference.SupplierLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SupplierLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SupplierLoginResult;
        
        public SupplierLoginResponseBody() {
        }
        
        public SupplierLoginResponseBody(string SupplierLoginResult) {
            this.SupplierLoginResult = SupplierLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SupplierServiceSoapChannel : SPC_Web.SupplierServiceReference.SupplierServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierServiceSoapClient : System.ServiceModel.ClientBase<SPC_Web.SupplierServiceReference.SupplierServiceSoap>, SPC_Web.SupplierServiceReference.SupplierServiceSoap {
        
        public SupplierServiceSoapClient() {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.SupplierServiceReference.RegisterSupplierResponse SPC_Web.SupplierServiceReference.SupplierServiceSoap.RegisterSupplier(SPC_Web.SupplierServiceReference.RegisterSupplierRequest request) {
            return base.Channel.RegisterSupplier(request);
        }
        
        public string RegisterSupplier(string supplierName, string contactName, string address, string phoneNumber, string email) {
            SPC_Web.SupplierServiceReference.RegisterSupplierRequest inValue = new SPC_Web.SupplierServiceReference.RegisterSupplierRequest();
            inValue.Body = new SPC_Web.SupplierServiceReference.RegisterSupplierRequestBody();
            inValue.Body.supplierName = supplierName;
            inValue.Body.contactName = contactName;
            inValue.Body.address = address;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            SPC_Web.SupplierServiceReference.RegisterSupplierResponse retVal = ((SPC_Web.SupplierServiceReference.SupplierServiceSoap)(this)).RegisterSupplier(inValue);
            return retVal.Body.RegisterSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.SupplierServiceReference.RegisterSupplierResponse> SPC_Web.SupplierServiceReference.SupplierServiceSoap.RegisterSupplierAsync(SPC_Web.SupplierServiceReference.RegisterSupplierRequest request) {
            return base.Channel.RegisterSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.SupplierServiceReference.RegisterSupplierResponse> RegisterSupplierAsync(string supplierName, string contactName, string address, string phoneNumber, string email) {
            SPC_Web.SupplierServiceReference.RegisterSupplierRequest inValue = new SPC_Web.SupplierServiceReference.RegisterSupplierRequest();
            inValue.Body = new SPC_Web.SupplierServiceReference.RegisterSupplierRequestBody();
            inValue.Body.supplierName = supplierName;
            inValue.Body.contactName = contactName;
            inValue.Body.address = address;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            return ((SPC_Web.SupplierServiceReference.SupplierServiceSoap)(this)).RegisterSupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.SupplierServiceReference.SupplierLoginResponse SPC_Web.SupplierServiceReference.SupplierServiceSoap.SupplierLogin(SPC_Web.SupplierServiceReference.SupplierLoginRequest request) {
            return base.Channel.SupplierLogin(request);
        }
        
        public string SupplierLogin(string email, string password) {
            SPC_Web.SupplierServiceReference.SupplierLoginRequest inValue = new SPC_Web.SupplierServiceReference.SupplierLoginRequest();
            inValue.Body = new SPC_Web.SupplierServiceReference.SupplierLoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            SPC_Web.SupplierServiceReference.SupplierLoginResponse retVal = ((SPC_Web.SupplierServiceReference.SupplierServiceSoap)(this)).SupplierLogin(inValue);
            return retVal.Body.SupplierLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.SupplierServiceReference.SupplierLoginResponse> SPC_Web.SupplierServiceReference.SupplierServiceSoap.SupplierLoginAsync(SPC_Web.SupplierServiceReference.SupplierLoginRequest request) {
            return base.Channel.SupplierLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.SupplierServiceReference.SupplierLoginResponse> SupplierLoginAsync(string email, string password) {
            SPC_Web.SupplierServiceReference.SupplierLoginRequest inValue = new SPC_Web.SupplierServiceReference.SupplierLoginRequest();
            inValue.Body = new SPC_Web.SupplierServiceReference.SupplierLoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((SPC_Web.SupplierServiceReference.SupplierServiceSoap)(this)).SupplierLoginAsync(inValue);
        }
    }
}
