//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Web.RoleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoleServiceReference.RoleServiceSoap")]
    public interface RoleServiceSoap {
        
        // CODEGEN: Generating message contract since element name roleName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRole", ReplyAction="*")]
        SPC_Web.RoleServiceReference.AddRoleResponse AddRole(SPC_Web.RoleServiceReference.AddRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRole", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.AddRoleResponse> AddRoleAsync(SPC_Web.RoleServiceReference.AddRoleRequest request);
        
        // CODEGEN: Generating message contract since element name roleName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditRole", ReplyAction="*")]
        SPC_Web.RoleServiceReference.EditRoleResponse EditRole(SPC_Web.RoleServiceReference.EditRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditRole", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.EditRoleResponse> EditRoleAsync(SPC_Web.RoleServiceReference.EditRoleRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteRoleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRole", ReplyAction="*")]
        SPC_Web.RoleServiceReference.DeleteRoleResponse DeleteRole(SPC_Web.RoleServiceReference.DeleteRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRole", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.DeleteRoleResponse> DeleteRoleAsync(SPC_Web.RoleServiceReference.DeleteRoleRequest request);
        
        // CODEGEN: Generating message contract since element name ShowRolesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowRoles", ReplyAction="*")]
        SPC_Web.RoleServiceReference.ShowRolesResponse ShowRoles(SPC_Web.RoleServiceReference.ShowRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.ShowRolesResponse> ShowRolesAsync(SPC_Web.RoleServiceReference.ShowRolesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRole", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.RoleServiceReference.AddRoleRequestBody Body;
        
        public AddRoleRequest() {
        }
        
        public AddRoleRequest(SPC_Web.RoleServiceReference.AddRoleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRoleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string roleName;
        
        public AddRoleRequestBody() {
        }
        
        public AddRoleRequestBody(string roleName) {
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRoleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.RoleServiceReference.AddRoleResponseBody Body;
        
        public AddRoleResponse() {
        }
        
        public AddRoleResponse(SPC_Web.RoleServiceReference.AddRoleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRoleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddRoleResult;
        
        public AddRoleResponseBody() {
        }
        
        public AddRoleResponseBody(string AddRoleResult) {
            this.AddRoleResult = AddRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditRole", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.RoleServiceReference.EditRoleRequestBody Body;
        
        public EditRoleRequest() {
        }
        
        public EditRoleRequest(SPC_Web.RoleServiceReference.EditRoleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditRoleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int roleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roleName;
        
        public EditRoleRequestBody() {
        }
        
        public EditRoleRequestBody(int roleId, string roleName) {
            this.roleId = roleId;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditRoleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.RoleServiceReference.EditRoleResponseBody Body;
        
        public EditRoleResponse() {
        }
        
        public EditRoleResponse(SPC_Web.RoleServiceReference.EditRoleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditRoleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditRoleResult;
        
        public EditRoleResponseBody() {
        }
        
        public EditRoleResponseBody(string EditRoleResult) {
            this.EditRoleResult = EditRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRole", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.RoleServiceReference.DeleteRoleRequestBody Body;
        
        public DeleteRoleRequest() {
        }
        
        public DeleteRoleRequest(SPC_Web.RoleServiceReference.DeleteRoleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRoleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int roleId;
        
        public DeleteRoleRequestBody() {
        }
        
        public DeleteRoleRequestBody(int roleId) {
            this.roleId = roleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRoleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.RoleServiceReference.DeleteRoleResponseBody Body;
        
        public DeleteRoleResponse() {
        }
        
        public DeleteRoleResponse(SPC_Web.RoleServiceReference.DeleteRoleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRoleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteRoleResult;
        
        public DeleteRoleResponseBody() {
        }
        
        public DeleteRoleResponseBody(string DeleteRoleResult) {
            this.DeleteRoleResult = DeleteRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowRoles", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.RoleServiceReference.ShowRolesRequestBody Body;
        
        public ShowRolesRequest() {
        }
        
        public ShowRolesRequest(SPC_Web.RoleServiceReference.ShowRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowRolesRequestBody {
        
        public ShowRolesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowRolesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.RoleServiceReference.ShowRolesResponseBody Body;
        
        public ShowRolesResponse() {
        }
        
        public ShowRolesResponse(SPC_Web.RoleServiceReference.ShowRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowRolesResult;
        
        public ShowRolesResponseBody() {
        }
        
        public ShowRolesResponseBody(string ShowRolesResult) {
            this.ShowRolesResult = ShowRolesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RoleServiceSoapChannel : SPC_Web.RoleServiceReference.RoleServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoleServiceSoapClient : System.ServiceModel.ClientBase<SPC_Web.RoleServiceReference.RoleServiceSoap>, SPC_Web.RoleServiceReference.RoleServiceSoap {
        
        public RoleServiceSoapClient() {
        }
        
        public RoleServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoleServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.RoleServiceReference.AddRoleResponse SPC_Web.RoleServiceReference.RoleServiceSoap.AddRole(SPC_Web.RoleServiceReference.AddRoleRequest request) {
            return base.Channel.AddRole(request);
        }
        
        public string AddRole(string roleName) {
            SPC_Web.RoleServiceReference.AddRoleRequest inValue = new SPC_Web.RoleServiceReference.AddRoleRequest();
            inValue.Body = new SPC_Web.RoleServiceReference.AddRoleRequestBody();
            inValue.Body.roleName = roleName;
            SPC_Web.RoleServiceReference.AddRoleResponse retVal = ((SPC_Web.RoleServiceReference.RoleServiceSoap)(this)).AddRole(inValue);
            return retVal.Body.AddRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.AddRoleResponse> SPC_Web.RoleServiceReference.RoleServiceSoap.AddRoleAsync(SPC_Web.RoleServiceReference.AddRoleRequest request) {
            return base.Channel.AddRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.AddRoleResponse> AddRoleAsync(string roleName) {
            SPC_Web.RoleServiceReference.AddRoleRequest inValue = new SPC_Web.RoleServiceReference.AddRoleRequest();
            inValue.Body = new SPC_Web.RoleServiceReference.AddRoleRequestBody();
            inValue.Body.roleName = roleName;
            return ((SPC_Web.RoleServiceReference.RoleServiceSoap)(this)).AddRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.RoleServiceReference.EditRoleResponse SPC_Web.RoleServiceReference.RoleServiceSoap.EditRole(SPC_Web.RoleServiceReference.EditRoleRequest request) {
            return base.Channel.EditRole(request);
        }
        
        public string EditRole(int roleId, string roleName) {
            SPC_Web.RoleServiceReference.EditRoleRequest inValue = new SPC_Web.RoleServiceReference.EditRoleRequest();
            inValue.Body = new SPC_Web.RoleServiceReference.EditRoleRequestBody();
            inValue.Body.roleId = roleId;
            inValue.Body.roleName = roleName;
            SPC_Web.RoleServiceReference.EditRoleResponse retVal = ((SPC_Web.RoleServiceReference.RoleServiceSoap)(this)).EditRole(inValue);
            return retVal.Body.EditRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.EditRoleResponse> SPC_Web.RoleServiceReference.RoleServiceSoap.EditRoleAsync(SPC_Web.RoleServiceReference.EditRoleRequest request) {
            return base.Channel.EditRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.EditRoleResponse> EditRoleAsync(int roleId, string roleName) {
            SPC_Web.RoleServiceReference.EditRoleRequest inValue = new SPC_Web.RoleServiceReference.EditRoleRequest();
            inValue.Body = new SPC_Web.RoleServiceReference.EditRoleRequestBody();
            inValue.Body.roleId = roleId;
            inValue.Body.roleName = roleName;
            return ((SPC_Web.RoleServiceReference.RoleServiceSoap)(this)).EditRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.RoleServiceReference.DeleteRoleResponse SPC_Web.RoleServiceReference.RoleServiceSoap.DeleteRole(SPC_Web.RoleServiceReference.DeleteRoleRequest request) {
            return base.Channel.DeleteRole(request);
        }
        
        public string DeleteRole(int roleId) {
            SPC_Web.RoleServiceReference.DeleteRoleRequest inValue = new SPC_Web.RoleServiceReference.DeleteRoleRequest();
            inValue.Body = new SPC_Web.RoleServiceReference.DeleteRoleRequestBody();
            inValue.Body.roleId = roleId;
            SPC_Web.RoleServiceReference.DeleteRoleResponse retVal = ((SPC_Web.RoleServiceReference.RoleServiceSoap)(this)).DeleteRole(inValue);
            return retVal.Body.DeleteRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.DeleteRoleResponse> SPC_Web.RoleServiceReference.RoleServiceSoap.DeleteRoleAsync(SPC_Web.RoleServiceReference.DeleteRoleRequest request) {
            return base.Channel.DeleteRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.DeleteRoleResponse> DeleteRoleAsync(int roleId) {
            SPC_Web.RoleServiceReference.DeleteRoleRequest inValue = new SPC_Web.RoleServiceReference.DeleteRoleRequest();
            inValue.Body = new SPC_Web.RoleServiceReference.DeleteRoleRequestBody();
            inValue.Body.roleId = roleId;
            return ((SPC_Web.RoleServiceReference.RoleServiceSoap)(this)).DeleteRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.RoleServiceReference.ShowRolesResponse SPC_Web.RoleServiceReference.RoleServiceSoap.ShowRoles(SPC_Web.RoleServiceReference.ShowRolesRequest request) {
            return base.Channel.ShowRoles(request);
        }
        
        public string ShowRoles() {
            SPC_Web.RoleServiceReference.ShowRolesRequest inValue = new SPC_Web.RoleServiceReference.ShowRolesRequest();
            inValue.Body = new SPC_Web.RoleServiceReference.ShowRolesRequestBody();
            SPC_Web.RoleServiceReference.ShowRolesResponse retVal = ((SPC_Web.RoleServiceReference.RoleServiceSoap)(this)).ShowRoles(inValue);
            return retVal.Body.ShowRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.ShowRolesResponse> SPC_Web.RoleServiceReference.RoleServiceSoap.ShowRolesAsync(SPC_Web.RoleServiceReference.ShowRolesRequest request) {
            return base.Channel.ShowRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.RoleServiceReference.ShowRolesResponse> ShowRolesAsync() {
            SPC_Web.RoleServiceReference.ShowRolesRequest inValue = new SPC_Web.RoleServiceReference.ShowRolesRequest();
            inValue.Body = new SPC_Web.RoleServiceReference.ShowRolesRequestBody();
            return ((SPC_Web.RoleServiceReference.RoleServiceSoap)(this)).ShowRolesAsync(inValue);
        }
    }
}
