//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Web.WarehouseServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WarehouseServiceReference.WarehouseServiceSoap")]
    public interface WarehouseServiceSoap {
        
        // CODEGEN: Generating message contract since element name warehouseName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWarehouse", ReplyAction="*")]
        SPC_Web.WarehouseServiceReference.AddWarehouseResponse AddWarehouse(SPC_Web.WarehouseServiceReference.AddWarehouseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWarehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.AddWarehouseResponse> AddWarehouseAsync(SPC_Web.WarehouseServiceReference.AddWarehouseRequest request);
        
        // CODEGEN: Generating message contract since element name warehouseName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditWarehouse", ReplyAction="*")]
        SPC_Web.WarehouseServiceReference.EditWarehouseResponse EditWarehouse(SPC_Web.WarehouseServiceReference.EditWarehouseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditWarehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.EditWarehouseResponse> EditWarehouseAsync(SPC_Web.WarehouseServiceReference.EditWarehouseRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteWarehouseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteWarehouse", ReplyAction="*")]
        SPC_Web.WarehouseServiceReference.DeleteWarehouseResponse DeleteWarehouse(SPC_Web.WarehouseServiceReference.DeleteWarehouseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteWarehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.DeleteWarehouseResponse> DeleteWarehouseAsync(SPC_Web.WarehouseServiceReference.DeleteWarehouseRequest request);
        
        // CODEGEN: Generating message contract since element name ShowWarehousesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowWarehouses", ReplyAction="*")]
        SPC_Web.WarehouseServiceReference.ShowWarehousesResponse ShowWarehouses(SPC_Web.WarehouseServiceReference.ShowWarehousesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowWarehouses", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.ShowWarehousesResponse> ShowWarehousesAsync(SPC_Web.WarehouseServiceReference.ShowWarehousesRequest request);
        
        // CODEGEN: Generating message contract since element name warehouseName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchWarehouse", ReplyAction="*")]
        SPC_Web.WarehouseServiceReference.SearchWarehouseResponse SearchWarehouse(SPC_Web.WarehouseServiceReference.SearchWarehouseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchWarehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.SearchWarehouseResponse> SearchWarehouseAsync(SPC_Web.WarehouseServiceReference.SearchWarehouseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddWarehouseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddWarehouse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.WarehouseServiceReference.AddWarehouseRequestBody Body;
        
        public AddWarehouseRequest() {
        }
        
        public AddWarehouseRequest(SPC_Web.WarehouseServiceReference.AddWarehouseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddWarehouseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string warehouseName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string location;
        
        public AddWarehouseRequestBody() {
        }
        
        public AddWarehouseRequestBody(string warehouseName, string location) {
            this.warehouseName = warehouseName;
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddWarehouseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddWarehouseResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.WarehouseServiceReference.AddWarehouseResponseBody Body;
        
        public AddWarehouseResponse() {
        }
        
        public AddWarehouseResponse(SPC_Web.WarehouseServiceReference.AddWarehouseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddWarehouseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddWarehouseResult;
        
        public AddWarehouseResponseBody() {
        }
        
        public AddWarehouseResponseBody(string AddWarehouseResult) {
            this.AddWarehouseResult = AddWarehouseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditWarehouseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditWarehouse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.WarehouseServiceReference.EditWarehouseRequestBody Body;
        
        public EditWarehouseRequest() {
        }
        
        public EditWarehouseRequest(SPC_Web.WarehouseServiceReference.EditWarehouseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditWarehouseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int warehouseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string warehouseName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string location;
        
        public EditWarehouseRequestBody() {
        }
        
        public EditWarehouseRequestBody(int warehouseId, string warehouseName, string location) {
            this.warehouseId = warehouseId;
            this.warehouseName = warehouseName;
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditWarehouseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditWarehouseResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.WarehouseServiceReference.EditWarehouseResponseBody Body;
        
        public EditWarehouseResponse() {
        }
        
        public EditWarehouseResponse(SPC_Web.WarehouseServiceReference.EditWarehouseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditWarehouseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditWarehouseResult;
        
        public EditWarehouseResponseBody() {
        }
        
        public EditWarehouseResponseBody(string EditWarehouseResult) {
            this.EditWarehouseResult = EditWarehouseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteWarehouseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteWarehouse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.WarehouseServiceReference.DeleteWarehouseRequestBody Body;
        
        public DeleteWarehouseRequest() {
        }
        
        public DeleteWarehouseRequest(SPC_Web.WarehouseServiceReference.DeleteWarehouseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteWarehouseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int warehouseId;
        
        public DeleteWarehouseRequestBody() {
        }
        
        public DeleteWarehouseRequestBody(int warehouseId) {
            this.warehouseId = warehouseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteWarehouseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteWarehouseResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.WarehouseServiceReference.DeleteWarehouseResponseBody Body;
        
        public DeleteWarehouseResponse() {
        }
        
        public DeleteWarehouseResponse(SPC_Web.WarehouseServiceReference.DeleteWarehouseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteWarehouseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteWarehouseResult;
        
        public DeleteWarehouseResponseBody() {
        }
        
        public DeleteWarehouseResponseBody(string DeleteWarehouseResult) {
            this.DeleteWarehouseResult = DeleteWarehouseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowWarehousesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowWarehouses", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.WarehouseServiceReference.ShowWarehousesRequestBody Body;
        
        public ShowWarehousesRequest() {
        }
        
        public ShowWarehousesRequest(SPC_Web.WarehouseServiceReference.ShowWarehousesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowWarehousesRequestBody {
        
        public ShowWarehousesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowWarehousesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowWarehousesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.WarehouseServiceReference.ShowWarehousesResponseBody Body;
        
        public ShowWarehousesResponse() {
        }
        
        public ShowWarehousesResponse(SPC_Web.WarehouseServiceReference.ShowWarehousesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowWarehousesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowWarehousesResult;
        
        public ShowWarehousesResponseBody() {
        }
        
        public ShowWarehousesResponseBody(string ShowWarehousesResult) {
            this.ShowWarehousesResult = ShowWarehousesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchWarehouseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchWarehouse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.WarehouseServiceReference.SearchWarehouseRequestBody Body;
        
        public SearchWarehouseRequest() {
        }
        
        public SearchWarehouseRequest(SPC_Web.WarehouseServiceReference.SearchWarehouseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchWarehouseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> warehouseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string warehouseName;
        
        public SearchWarehouseRequestBody() {
        }
        
        public SearchWarehouseRequestBody(System.Nullable<int> warehouseId, string warehouseName) {
            this.warehouseId = warehouseId;
            this.warehouseName = warehouseName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchWarehouseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchWarehouseResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.WarehouseServiceReference.SearchWarehouseResponseBody Body;
        
        public SearchWarehouseResponse() {
        }
        
        public SearchWarehouseResponse(SPC_Web.WarehouseServiceReference.SearchWarehouseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchWarehouseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchWarehouseResult;
        
        public SearchWarehouseResponseBody() {
        }
        
        public SearchWarehouseResponseBody(string SearchWarehouseResult) {
            this.SearchWarehouseResult = SearchWarehouseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WarehouseServiceSoapChannel : SPC_Web.WarehouseServiceReference.WarehouseServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WarehouseServiceSoapClient : System.ServiceModel.ClientBase<SPC_Web.WarehouseServiceReference.WarehouseServiceSoap>, SPC_Web.WarehouseServiceReference.WarehouseServiceSoap {
        
        public WarehouseServiceSoapClient() {
        }
        
        public WarehouseServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WarehouseServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.WarehouseServiceReference.AddWarehouseResponse SPC_Web.WarehouseServiceReference.WarehouseServiceSoap.AddWarehouse(SPC_Web.WarehouseServiceReference.AddWarehouseRequest request) {
            return base.Channel.AddWarehouse(request);
        }
        
        public string AddWarehouse(string warehouseName, string location) {
            SPC_Web.WarehouseServiceReference.AddWarehouseRequest inValue = new SPC_Web.WarehouseServiceReference.AddWarehouseRequest();
            inValue.Body = new SPC_Web.WarehouseServiceReference.AddWarehouseRequestBody();
            inValue.Body.warehouseName = warehouseName;
            inValue.Body.location = location;
            SPC_Web.WarehouseServiceReference.AddWarehouseResponse retVal = ((SPC_Web.WarehouseServiceReference.WarehouseServiceSoap)(this)).AddWarehouse(inValue);
            return retVal.Body.AddWarehouseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.AddWarehouseResponse> SPC_Web.WarehouseServiceReference.WarehouseServiceSoap.AddWarehouseAsync(SPC_Web.WarehouseServiceReference.AddWarehouseRequest request) {
            return base.Channel.AddWarehouseAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.AddWarehouseResponse> AddWarehouseAsync(string warehouseName, string location) {
            SPC_Web.WarehouseServiceReference.AddWarehouseRequest inValue = new SPC_Web.WarehouseServiceReference.AddWarehouseRequest();
            inValue.Body = new SPC_Web.WarehouseServiceReference.AddWarehouseRequestBody();
            inValue.Body.warehouseName = warehouseName;
            inValue.Body.location = location;
            return ((SPC_Web.WarehouseServiceReference.WarehouseServiceSoap)(this)).AddWarehouseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.WarehouseServiceReference.EditWarehouseResponse SPC_Web.WarehouseServiceReference.WarehouseServiceSoap.EditWarehouse(SPC_Web.WarehouseServiceReference.EditWarehouseRequest request) {
            return base.Channel.EditWarehouse(request);
        }
        
        public string EditWarehouse(int warehouseId, string warehouseName, string location) {
            SPC_Web.WarehouseServiceReference.EditWarehouseRequest inValue = new SPC_Web.WarehouseServiceReference.EditWarehouseRequest();
            inValue.Body = new SPC_Web.WarehouseServiceReference.EditWarehouseRequestBody();
            inValue.Body.warehouseId = warehouseId;
            inValue.Body.warehouseName = warehouseName;
            inValue.Body.location = location;
            SPC_Web.WarehouseServiceReference.EditWarehouseResponse retVal = ((SPC_Web.WarehouseServiceReference.WarehouseServiceSoap)(this)).EditWarehouse(inValue);
            return retVal.Body.EditWarehouseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.EditWarehouseResponse> SPC_Web.WarehouseServiceReference.WarehouseServiceSoap.EditWarehouseAsync(SPC_Web.WarehouseServiceReference.EditWarehouseRequest request) {
            return base.Channel.EditWarehouseAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.EditWarehouseResponse> EditWarehouseAsync(int warehouseId, string warehouseName, string location) {
            SPC_Web.WarehouseServiceReference.EditWarehouseRequest inValue = new SPC_Web.WarehouseServiceReference.EditWarehouseRequest();
            inValue.Body = new SPC_Web.WarehouseServiceReference.EditWarehouseRequestBody();
            inValue.Body.warehouseId = warehouseId;
            inValue.Body.warehouseName = warehouseName;
            inValue.Body.location = location;
            return ((SPC_Web.WarehouseServiceReference.WarehouseServiceSoap)(this)).EditWarehouseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.WarehouseServiceReference.DeleteWarehouseResponse SPC_Web.WarehouseServiceReference.WarehouseServiceSoap.DeleteWarehouse(SPC_Web.WarehouseServiceReference.DeleteWarehouseRequest request) {
            return base.Channel.DeleteWarehouse(request);
        }
        
        public string DeleteWarehouse(int warehouseId) {
            SPC_Web.WarehouseServiceReference.DeleteWarehouseRequest inValue = new SPC_Web.WarehouseServiceReference.DeleteWarehouseRequest();
            inValue.Body = new SPC_Web.WarehouseServiceReference.DeleteWarehouseRequestBody();
            inValue.Body.warehouseId = warehouseId;
            SPC_Web.WarehouseServiceReference.DeleteWarehouseResponse retVal = ((SPC_Web.WarehouseServiceReference.WarehouseServiceSoap)(this)).DeleteWarehouse(inValue);
            return retVal.Body.DeleteWarehouseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.DeleteWarehouseResponse> SPC_Web.WarehouseServiceReference.WarehouseServiceSoap.DeleteWarehouseAsync(SPC_Web.WarehouseServiceReference.DeleteWarehouseRequest request) {
            return base.Channel.DeleteWarehouseAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.DeleteWarehouseResponse> DeleteWarehouseAsync(int warehouseId) {
            SPC_Web.WarehouseServiceReference.DeleteWarehouseRequest inValue = new SPC_Web.WarehouseServiceReference.DeleteWarehouseRequest();
            inValue.Body = new SPC_Web.WarehouseServiceReference.DeleteWarehouseRequestBody();
            inValue.Body.warehouseId = warehouseId;
            return ((SPC_Web.WarehouseServiceReference.WarehouseServiceSoap)(this)).DeleteWarehouseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.WarehouseServiceReference.ShowWarehousesResponse SPC_Web.WarehouseServiceReference.WarehouseServiceSoap.ShowWarehouses(SPC_Web.WarehouseServiceReference.ShowWarehousesRequest request) {
            return base.Channel.ShowWarehouses(request);
        }
        
        public string ShowWarehouses() {
            SPC_Web.WarehouseServiceReference.ShowWarehousesRequest inValue = new SPC_Web.WarehouseServiceReference.ShowWarehousesRequest();
            inValue.Body = new SPC_Web.WarehouseServiceReference.ShowWarehousesRequestBody();
            SPC_Web.WarehouseServiceReference.ShowWarehousesResponse retVal = ((SPC_Web.WarehouseServiceReference.WarehouseServiceSoap)(this)).ShowWarehouses(inValue);
            return retVal.Body.ShowWarehousesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.ShowWarehousesResponse> SPC_Web.WarehouseServiceReference.WarehouseServiceSoap.ShowWarehousesAsync(SPC_Web.WarehouseServiceReference.ShowWarehousesRequest request) {
            return base.Channel.ShowWarehousesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.ShowWarehousesResponse> ShowWarehousesAsync() {
            SPC_Web.WarehouseServiceReference.ShowWarehousesRequest inValue = new SPC_Web.WarehouseServiceReference.ShowWarehousesRequest();
            inValue.Body = new SPC_Web.WarehouseServiceReference.ShowWarehousesRequestBody();
            return ((SPC_Web.WarehouseServiceReference.WarehouseServiceSoap)(this)).ShowWarehousesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.WarehouseServiceReference.SearchWarehouseResponse SPC_Web.WarehouseServiceReference.WarehouseServiceSoap.SearchWarehouse(SPC_Web.WarehouseServiceReference.SearchWarehouseRequest request) {
            return base.Channel.SearchWarehouse(request);
        }
        
        public string SearchWarehouse(System.Nullable<int> warehouseId, string warehouseName) {
            SPC_Web.WarehouseServiceReference.SearchWarehouseRequest inValue = new SPC_Web.WarehouseServiceReference.SearchWarehouseRequest();
            inValue.Body = new SPC_Web.WarehouseServiceReference.SearchWarehouseRequestBody();
            inValue.Body.warehouseId = warehouseId;
            inValue.Body.warehouseName = warehouseName;
            SPC_Web.WarehouseServiceReference.SearchWarehouseResponse retVal = ((SPC_Web.WarehouseServiceReference.WarehouseServiceSoap)(this)).SearchWarehouse(inValue);
            return retVal.Body.SearchWarehouseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.SearchWarehouseResponse> SPC_Web.WarehouseServiceReference.WarehouseServiceSoap.SearchWarehouseAsync(SPC_Web.WarehouseServiceReference.SearchWarehouseRequest request) {
            return base.Channel.SearchWarehouseAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.WarehouseServiceReference.SearchWarehouseResponse> SearchWarehouseAsync(System.Nullable<int> warehouseId, string warehouseName) {
            SPC_Web.WarehouseServiceReference.SearchWarehouseRequest inValue = new SPC_Web.WarehouseServiceReference.SearchWarehouseRequest();
            inValue.Body = new SPC_Web.WarehouseServiceReference.SearchWarehouseRequestBody();
            inValue.Body.warehouseId = warehouseId;
            inValue.Body.warehouseName = warehouseName;
            return ((SPC_Web.WarehouseServiceReference.WarehouseServiceSoap)(this)).SearchWarehouseAsync(inValue);
        }
    }
}
