//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Web.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.UserServiceSoap")]
    public interface UserServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        SPC_Web.UserServiceReference.AddUserResponse AddUser(SPC_Web.UserServiceReference.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.UserServiceReference.AddUserResponse> AddUserAsync(SPC_Web.UserServiceReference.AddUserRequest request);
        
        // CODEGEN: Generating message contract since element name userIdStr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditUser", ReplyAction="*")]
        SPC_Web.UserServiceReference.EditUserResponse EditUser(SPC_Web.UserServiceReference.EditUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.UserServiceReference.EditUserResponse> EditUserAsync(SPC_Web.UserServiceReference.EditUserRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        SPC_Web.UserServiceReference.DeleteUserResponse DeleteUser(SPC_Web.UserServiceReference.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.UserServiceReference.DeleteUserResponse> DeleteUserAsync(SPC_Web.UserServiceReference.DeleteUserRequest request);
        
        // CODEGEN: Generating message contract since element name ShowUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowUsers", ReplyAction="*")]
        SPC_Web.UserServiceReference.ShowUsersResponse ShowUsers(SPC_Web.UserServiceReference.ShowUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.UserServiceReference.ShowUsersResponse> ShowUsersAsync(SPC_Web.UserServiceReference.ShowUsersRequest request);
        
        // CODEGEN: Generating message contract since element name searchTerm from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchUsers", ReplyAction="*")]
        SPC_Web.UserServiceReference.SearchUsersResponse SearchUsers(SPC_Web.UserServiceReference.SearchUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.UserServiceReference.SearchUsersResponse> SearchUsersAsync(SPC_Web.UserServiceReference.SearchUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.UserServiceReference.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(SPC_Web.UserServiceReference.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string passwordHash;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int roleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string isActive;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string userName, string email, string passwordHash, int roleId, string isActive) {
            this.userName = userName;
            this.email = email;
            this.passwordHash = passwordHash;
            this.roleId = roleId;
            this.isActive = isActive;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.UserServiceReference.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(SPC_Web.UserServiceReference.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(string AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditUser", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.UserServiceReference.EditUserRequestBody Body;
        
        public EditUserRequest() {
        }
        
        public EditUserRequest(SPC_Web.UserServiceReference.EditUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userIdStr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string passwordHash;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int roleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isActive;
        
        public EditUserRequestBody() {
        }
        
        public EditUserRequestBody(string userIdStr, string userName, string email, string passwordHash, int roleId, bool isActive) {
            this.userIdStr = userIdStr;
            this.userName = userName;
            this.email = email;
            this.passwordHash = passwordHash;
            this.roleId = roleId;
            this.isActive = isActive;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.UserServiceReference.EditUserResponseBody Body;
        
        public EditUserResponse() {
        }
        
        public EditUserResponse(SPC_Web.UserServiceReference.EditUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditUserResult;
        
        public EditUserResponseBody() {
        }
        
        public EditUserResponseBody(string EditUserResult) {
            this.EditUserResult = EditUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.UserServiceReference.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(SPC_Web.UserServiceReference.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.UserServiceReference.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(SPC_Web.UserServiceReference.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteUserResult;
        
        public DeleteUserResponseBody() {
        }
        
        public DeleteUserResponseBody(string DeleteUserResult) {
            this.DeleteUserResult = DeleteUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowUsers", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.UserServiceReference.ShowUsersRequestBody Body;
        
        public ShowUsersRequest() {
        }
        
        public ShowUsersRequest(SPC_Web.UserServiceReference.ShowUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowUsersRequestBody {
        
        public ShowUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.UserServiceReference.ShowUsersResponseBody Body;
        
        public ShowUsersResponse() {
        }
        
        public ShowUsersResponse(SPC_Web.UserServiceReference.ShowUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowUsersResult;
        
        public ShowUsersResponseBody() {
        }
        
        public ShowUsersResponseBody(string ShowUsersResult) {
            this.ShowUsersResult = ShowUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUsers", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.UserServiceReference.SearchUsersRequestBody Body;
        
        public SearchUsersRequest() {
        }
        
        public SearchUsersRequest(SPC_Web.UserServiceReference.SearchUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchTerm;
        
        public SearchUsersRequestBody() {
        }
        
        public SearchUsersRequestBody(string searchTerm) {
            this.searchTerm = searchTerm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.UserServiceReference.SearchUsersResponseBody Body;
        
        public SearchUsersResponse() {
        }
        
        public SearchUsersResponse(SPC_Web.UserServiceReference.SearchUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchUsersResult;
        
        public SearchUsersResponseBody() {
        }
        
        public SearchUsersResponseBody(string SearchUsersResult) {
            this.SearchUsersResult = SearchUsersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : SPC_Web.UserServiceReference.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<SPC_Web.UserServiceReference.UserServiceSoap>, SPC_Web.UserServiceReference.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.UserServiceReference.AddUserResponse SPC_Web.UserServiceReference.UserServiceSoap.AddUser(SPC_Web.UserServiceReference.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public string AddUser(string userName, string email, string passwordHash, int roleId, string isActive) {
            SPC_Web.UserServiceReference.AddUserRequest inValue = new SPC_Web.UserServiceReference.AddUserRequest();
            inValue.Body = new SPC_Web.UserServiceReference.AddUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.email = email;
            inValue.Body.passwordHash = passwordHash;
            inValue.Body.roleId = roleId;
            inValue.Body.isActive = isActive;
            SPC_Web.UserServiceReference.AddUserResponse retVal = ((SPC_Web.UserServiceReference.UserServiceSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.UserServiceReference.AddUserResponse> SPC_Web.UserServiceReference.UserServiceSoap.AddUserAsync(SPC_Web.UserServiceReference.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.UserServiceReference.AddUserResponse> AddUserAsync(string userName, string email, string passwordHash, int roleId, string isActive) {
            SPC_Web.UserServiceReference.AddUserRequest inValue = new SPC_Web.UserServiceReference.AddUserRequest();
            inValue.Body = new SPC_Web.UserServiceReference.AddUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.email = email;
            inValue.Body.passwordHash = passwordHash;
            inValue.Body.roleId = roleId;
            inValue.Body.isActive = isActive;
            return ((SPC_Web.UserServiceReference.UserServiceSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.UserServiceReference.EditUserResponse SPC_Web.UserServiceReference.UserServiceSoap.EditUser(SPC_Web.UserServiceReference.EditUserRequest request) {
            return base.Channel.EditUser(request);
        }
        
        public string EditUser(string userIdStr, string userName, string email, string passwordHash, int roleId, bool isActive) {
            SPC_Web.UserServiceReference.EditUserRequest inValue = new SPC_Web.UserServiceReference.EditUserRequest();
            inValue.Body = new SPC_Web.UserServiceReference.EditUserRequestBody();
            inValue.Body.userIdStr = userIdStr;
            inValue.Body.userName = userName;
            inValue.Body.email = email;
            inValue.Body.passwordHash = passwordHash;
            inValue.Body.roleId = roleId;
            inValue.Body.isActive = isActive;
            SPC_Web.UserServiceReference.EditUserResponse retVal = ((SPC_Web.UserServiceReference.UserServiceSoap)(this)).EditUser(inValue);
            return retVal.Body.EditUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.UserServiceReference.EditUserResponse> SPC_Web.UserServiceReference.UserServiceSoap.EditUserAsync(SPC_Web.UserServiceReference.EditUserRequest request) {
            return base.Channel.EditUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.UserServiceReference.EditUserResponse> EditUserAsync(string userIdStr, string userName, string email, string passwordHash, int roleId, bool isActive) {
            SPC_Web.UserServiceReference.EditUserRequest inValue = new SPC_Web.UserServiceReference.EditUserRequest();
            inValue.Body = new SPC_Web.UserServiceReference.EditUserRequestBody();
            inValue.Body.userIdStr = userIdStr;
            inValue.Body.userName = userName;
            inValue.Body.email = email;
            inValue.Body.passwordHash = passwordHash;
            inValue.Body.roleId = roleId;
            inValue.Body.isActive = isActive;
            return ((SPC_Web.UserServiceReference.UserServiceSoap)(this)).EditUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.UserServiceReference.DeleteUserResponse SPC_Web.UserServiceReference.UserServiceSoap.DeleteUser(SPC_Web.UserServiceReference.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public string DeleteUser(int userId) {
            SPC_Web.UserServiceReference.DeleteUserRequest inValue = new SPC_Web.UserServiceReference.DeleteUserRequest();
            inValue.Body = new SPC_Web.UserServiceReference.DeleteUserRequestBody();
            inValue.Body.userId = userId;
            SPC_Web.UserServiceReference.DeleteUserResponse retVal = ((SPC_Web.UserServiceReference.UserServiceSoap)(this)).DeleteUser(inValue);
            return retVal.Body.DeleteUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.UserServiceReference.DeleteUserResponse> SPC_Web.UserServiceReference.UserServiceSoap.DeleteUserAsync(SPC_Web.UserServiceReference.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.UserServiceReference.DeleteUserResponse> DeleteUserAsync(int userId) {
            SPC_Web.UserServiceReference.DeleteUserRequest inValue = new SPC_Web.UserServiceReference.DeleteUserRequest();
            inValue.Body = new SPC_Web.UserServiceReference.DeleteUserRequestBody();
            inValue.Body.userId = userId;
            return ((SPC_Web.UserServiceReference.UserServiceSoap)(this)).DeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.UserServiceReference.ShowUsersResponse SPC_Web.UserServiceReference.UserServiceSoap.ShowUsers(SPC_Web.UserServiceReference.ShowUsersRequest request) {
            return base.Channel.ShowUsers(request);
        }
        
        public string ShowUsers() {
            SPC_Web.UserServiceReference.ShowUsersRequest inValue = new SPC_Web.UserServiceReference.ShowUsersRequest();
            inValue.Body = new SPC_Web.UserServiceReference.ShowUsersRequestBody();
            SPC_Web.UserServiceReference.ShowUsersResponse retVal = ((SPC_Web.UserServiceReference.UserServiceSoap)(this)).ShowUsers(inValue);
            return retVal.Body.ShowUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.UserServiceReference.ShowUsersResponse> SPC_Web.UserServiceReference.UserServiceSoap.ShowUsersAsync(SPC_Web.UserServiceReference.ShowUsersRequest request) {
            return base.Channel.ShowUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.UserServiceReference.ShowUsersResponse> ShowUsersAsync() {
            SPC_Web.UserServiceReference.ShowUsersRequest inValue = new SPC_Web.UserServiceReference.ShowUsersRequest();
            inValue.Body = new SPC_Web.UserServiceReference.ShowUsersRequestBody();
            return ((SPC_Web.UserServiceReference.UserServiceSoap)(this)).ShowUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.UserServiceReference.SearchUsersResponse SPC_Web.UserServiceReference.UserServiceSoap.SearchUsers(SPC_Web.UserServiceReference.SearchUsersRequest request) {
            return base.Channel.SearchUsers(request);
        }
        
        public string SearchUsers(string searchTerm) {
            SPC_Web.UserServiceReference.SearchUsersRequest inValue = new SPC_Web.UserServiceReference.SearchUsersRequest();
            inValue.Body = new SPC_Web.UserServiceReference.SearchUsersRequestBody();
            inValue.Body.searchTerm = searchTerm;
            SPC_Web.UserServiceReference.SearchUsersResponse retVal = ((SPC_Web.UserServiceReference.UserServiceSoap)(this)).SearchUsers(inValue);
            return retVal.Body.SearchUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.UserServiceReference.SearchUsersResponse> SPC_Web.UserServiceReference.UserServiceSoap.SearchUsersAsync(SPC_Web.UserServiceReference.SearchUsersRequest request) {
            return base.Channel.SearchUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.UserServiceReference.SearchUsersResponse> SearchUsersAsync(string searchTerm) {
            SPC_Web.UserServiceReference.SearchUsersRequest inValue = new SPC_Web.UserServiceReference.SearchUsersRequest();
            inValue.Body = new SPC_Web.UserServiceReference.SearchUsersRequestBody();
            inValue.Body.searchTerm = searchTerm;
            return ((SPC_Web.UserServiceReference.UserServiceSoap)(this)).SearchUsersAsync(inValue);
        }
    }
}
