//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Web.OrderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference.OrderServiceSoap")]
    public interface OrderServiceSoap {
        
        // CODEGEN: Generating message contract since element name status from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOrder", ReplyAction="*")]
        SPC_Web.OrderServiceReference.AddOrderResponse AddOrder(SPC_Web.OrderServiceReference.AddOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.AddOrderResponse> AddOrderAsync(SPC_Web.OrderServiceReference.AddOrderRequest request);
        
        // CODEGEN: Generating message contract since element name status from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditOrder", ReplyAction="*")]
        SPC_Web.OrderServiceReference.EditOrderResponse EditOrder(SPC_Web.OrderServiceReference.EditOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.EditOrderResponse> EditOrderAsync(SPC_Web.OrderServiceReference.EditOrderRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteOrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrder", ReplyAction="*")]
        SPC_Web.OrderServiceReference.DeleteOrderResponse DeleteOrder(SPC_Web.OrderServiceReference.DeleteOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.DeleteOrderResponse> DeleteOrderAsync(SPC_Web.OrderServiceReference.DeleteOrderRequest request);
        
        // CODEGEN: Generating message contract since element name newStatus from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeOrderStatus", ReplyAction="*")]
        SPC_Web.OrderServiceReference.ChangeOrderStatusResponse ChangeOrderStatus(SPC_Web.OrderServiceReference.ChangeOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.ChangeOrderStatusResponse> ChangeOrderStatusAsync(SPC_Web.OrderServiceReference.ChangeOrderStatusRequest request);
        
        // CODEGEN: Generating message contract since element name ShowOrdersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowOrders", ReplyAction="*")]
        SPC_Web.OrderServiceReference.ShowOrdersResponse ShowOrders(SPC_Web.OrderServiceReference.ShowOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.ShowOrdersResponse> ShowOrdersAsync(SPC_Web.OrderServiceReference.ShowOrdersRequest request);
        
        // CODEGEN: Generating message contract since element name searchTerm from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchOrders", ReplyAction="*")]
        SPC_Web.OrderServiceReference.SearchOrdersResponse SearchOrders(SPC_Web.OrderServiceReference.SearchOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.SearchOrdersResponse> SearchOrdersAsync(SPC_Web.OrderServiceReference.SearchOrdersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrder", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.AddOrderRequestBody Body;
        
        public AddOrderRequest() {
        }
        
        public AddOrderRequest(SPC_Web.OrderServiceReference.AddOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime orderDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pharmacyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal totalAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal pricePerPiece;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string drugName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int quantity;
        
        public AddOrderRequestBody() {
        }
        
        public AddOrderRequestBody(System.DateTime orderDate, string status, int pharmacyId, decimal totalAmount, decimal pricePerPiece, string drugName, int quantity) {
            this.orderDate = orderDate;
            this.status = status;
            this.pharmacyId = pharmacyId;
            this.totalAmount = totalAmount;
            this.pricePerPiece = pricePerPiece;
            this.drugName = drugName;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.AddOrderResponseBody Body;
        
        public AddOrderResponse() {
        }
        
        public AddOrderResponse(SPC_Web.OrderServiceReference.AddOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddOrderResult;
        
        public AddOrderResponseBody() {
        }
        
        public AddOrderResponseBody(string AddOrderResult) {
            this.AddOrderResult = AddOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditOrder", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.EditOrderRequestBody Body;
        
        public EditOrderRequest() {
        }
        
        public EditOrderRequest(SPC_Web.OrderServiceReference.EditOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime orderDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pharmacyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal totalAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal pricePerPiece;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string drugName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int quantity;
        
        public EditOrderRequestBody() {
        }
        
        public EditOrderRequestBody(int orderId, System.DateTime orderDate, string status, int pharmacyId, decimal totalAmount, decimal pricePerPiece, string drugName, int quantity) {
            this.orderId = orderId;
            this.orderDate = orderDate;
            this.status = status;
            this.pharmacyId = pharmacyId;
            this.totalAmount = totalAmount;
            this.pricePerPiece = pricePerPiece;
            this.drugName = drugName;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.EditOrderResponseBody Body;
        
        public EditOrderResponse() {
        }
        
        public EditOrderResponse(SPC_Web.OrderServiceReference.EditOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditOrderResult;
        
        public EditOrderResponseBody() {
        }
        
        public EditOrderResponseBody(string EditOrderResult) {
            this.EditOrderResult = EditOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrder", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.DeleteOrderRequestBody Body;
        
        public DeleteOrderRequest() {
        }
        
        public DeleteOrderRequest(SPC_Web.OrderServiceReference.DeleteOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        public DeleteOrderRequestBody() {
        }
        
        public DeleteOrderRequestBody(int orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.DeleteOrderResponseBody Body;
        
        public DeleteOrderResponse() {
        }
        
        public DeleteOrderResponse(SPC_Web.OrderServiceReference.DeleteOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteOrderResult;
        
        public DeleteOrderResponseBody() {
        }
        
        public DeleteOrderResponseBody(string DeleteOrderResult) {
            this.DeleteOrderResult = DeleteOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeOrderStatus", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.ChangeOrderStatusRequestBody Body;
        
        public ChangeOrderStatusRequest() {
        }
        
        public ChangeOrderStatusRequest(SPC_Web.OrderServiceReference.ChangeOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newStatus;
        
        public ChangeOrderStatusRequestBody() {
        }
        
        public ChangeOrderStatusRequestBody(int orderId, string newStatus) {
            this.orderId = orderId;
            this.newStatus = newStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeOrderStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.ChangeOrderStatusResponseBody Body;
        
        public ChangeOrderStatusResponse() {
        }
        
        public ChangeOrderStatusResponse(SPC_Web.OrderServiceReference.ChangeOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeOrderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChangeOrderStatusResult;
        
        public ChangeOrderStatusResponseBody() {
        }
        
        public ChangeOrderStatusResponseBody(string ChangeOrderStatusResult) {
            this.ChangeOrderStatusResult = ChangeOrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowOrders", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.ShowOrdersRequestBody Body;
        
        public ShowOrdersRequest() {
        }
        
        public ShowOrdersRequest(SPC_Web.OrderServiceReference.ShowOrdersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowOrdersRequestBody {
        
        public ShowOrdersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowOrdersResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.ShowOrdersResponseBody Body;
        
        public ShowOrdersResponse() {
        }
        
        public ShowOrdersResponse(SPC_Web.OrderServiceReference.ShowOrdersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowOrdersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowOrdersResult;
        
        public ShowOrdersResponseBody() {
        }
        
        public ShowOrdersResponseBody(string ShowOrdersResult) {
            this.ShowOrdersResult = ShowOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchOrders", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.SearchOrdersRequestBody Body;
        
        public SearchOrdersRequest() {
        }
        
        public SearchOrdersRequest(SPC_Web.OrderServiceReference.SearchOrdersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchOrdersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchTerm;
        
        public SearchOrdersRequestBody() {
        }
        
        public SearchOrdersRequestBody(string searchTerm) {
            this.searchTerm = searchTerm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchOrdersResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.OrderServiceReference.SearchOrdersResponseBody Body;
        
        public SearchOrdersResponse() {
        }
        
        public SearchOrdersResponse(SPC_Web.OrderServiceReference.SearchOrdersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchOrdersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchOrdersResult;
        
        public SearchOrdersResponseBody() {
        }
        
        public SearchOrdersResponseBody(string SearchOrdersResult) {
            this.SearchOrdersResult = SearchOrdersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderServiceSoapChannel : SPC_Web.OrderServiceReference.OrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceSoapClient : System.ServiceModel.ClientBase<SPC_Web.OrderServiceReference.OrderServiceSoap>, SPC_Web.OrderServiceReference.OrderServiceSoap {
        
        public OrderServiceSoapClient() {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.OrderServiceReference.AddOrderResponse SPC_Web.OrderServiceReference.OrderServiceSoap.AddOrder(SPC_Web.OrderServiceReference.AddOrderRequest request) {
            return base.Channel.AddOrder(request);
        }
        
        public string AddOrder(System.DateTime orderDate, string status, int pharmacyId, decimal totalAmount, decimal pricePerPiece, string drugName, int quantity) {
            SPC_Web.OrderServiceReference.AddOrderRequest inValue = new SPC_Web.OrderServiceReference.AddOrderRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.AddOrderRequestBody();
            inValue.Body.orderDate = orderDate;
            inValue.Body.status = status;
            inValue.Body.pharmacyId = pharmacyId;
            inValue.Body.totalAmount = totalAmount;
            inValue.Body.pricePerPiece = pricePerPiece;
            inValue.Body.drugName = drugName;
            inValue.Body.quantity = quantity;
            SPC_Web.OrderServiceReference.AddOrderResponse retVal = ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).AddOrder(inValue);
            return retVal.Body.AddOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.AddOrderResponse> SPC_Web.OrderServiceReference.OrderServiceSoap.AddOrderAsync(SPC_Web.OrderServiceReference.AddOrderRequest request) {
            return base.Channel.AddOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.AddOrderResponse> AddOrderAsync(System.DateTime orderDate, string status, int pharmacyId, decimal totalAmount, decimal pricePerPiece, string drugName, int quantity) {
            SPC_Web.OrderServiceReference.AddOrderRequest inValue = new SPC_Web.OrderServiceReference.AddOrderRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.AddOrderRequestBody();
            inValue.Body.orderDate = orderDate;
            inValue.Body.status = status;
            inValue.Body.pharmacyId = pharmacyId;
            inValue.Body.totalAmount = totalAmount;
            inValue.Body.pricePerPiece = pricePerPiece;
            inValue.Body.drugName = drugName;
            inValue.Body.quantity = quantity;
            return ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).AddOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.OrderServiceReference.EditOrderResponse SPC_Web.OrderServiceReference.OrderServiceSoap.EditOrder(SPC_Web.OrderServiceReference.EditOrderRequest request) {
            return base.Channel.EditOrder(request);
        }
        
        public string EditOrder(int orderId, System.DateTime orderDate, string status, int pharmacyId, decimal totalAmount, decimal pricePerPiece, string drugName, int quantity) {
            SPC_Web.OrderServiceReference.EditOrderRequest inValue = new SPC_Web.OrderServiceReference.EditOrderRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.EditOrderRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.orderDate = orderDate;
            inValue.Body.status = status;
            inValue.Body.pharmacyId = pharmacyId;
            inValue.Body.totalAmount = totalAmount;
            inValue.Body.pricePerPiece = pricePerPiece;
            inValue.Body.drugName = drugName;
            inValue.Body.quantity = quantity;
            SPC_Web.OrderServiceReference.EditOrderResponse retVal = ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).EditOrder(inValue);
            return retVal.Body.EditOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.EditOrderResponse> SPC_Web.OrderServiceReference.OrderServiceSoap.EditOrderAsync(SPC_Web.OrderServiceReference.EditOrderRequest request) {
            return base.Channel.EditOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.EditOrderResponse> EditOrderAsync(int orderId, System.DateTime orderDate, string status, int pharmacyId, decimal totalAmount, decimal pricePerPiece, string drugName, int quantity) {
            SPC_Web.OrderServiceReference.EditOrderRequest inValue = new SPC_Web.OrderServiceReference.EditOrderRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.EditOrderRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.orderDate = orderDate;
            inValue.Body.status = status;
            inValue.Body.pharmacyId = pharmacyId;
            inValue.Body.totalAmount = totalAmount;
            inValue.Body.pricePerPiece = pricePerPiece;
            inValue.Body.drugName = drugName;
            inValue.Body.quantity = quantity;
            return ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).EditOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.OrderServiceReference.DeleteOrderResponse SPC_Web.OrderServiceReference.OrderServiceSoap.DeleteOrder(SPC_Web.OrderServiceReference.DeleteOrderRequest request) {
            return base.Channel.DeleteOrder(request);
        }
        
        public string DeleteOrder(int orderId) {
            SPC_Web.OrderServiceReference.DeleteOrderRequest inValue = new SPC_Web.OrderServiceReference.DeleteOrderRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.DeleteOrderRequestBody();
            inValue.Body.orderId = orderId;
            SPC_Web.OrderServiceReference.DeleteOrderResponse retVal = ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).DeleteOrder(inValue);
            return retVal.Body.DeleteOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.DeleteOrderResponse> SPC_Web.OrderServiceReference.OrderServiceSoap.DeleteOrderAsync(SPC_Web.OrderServiceReference.DeleteOrderRequest request) {
            return base.Channel.DeleteOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.DeleteOrderResponse> DeleteOrderAsync(int orderId) {
            SPC_Web.OrderServiceReference.DeleteOrderRequest inValue = new SPC_Web.OrderServiceReference.DeleteOrderRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.DeleteOrderRequestBody();
            inValue.Body.orderId = orderId;
            return ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).DeleteOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.OrderServiceReference.ChangeOrderStatusResponse SPC_Web.OrderServiceReference.OrderServiceSoap.ChangeOrderStatus(SPC_Web.OrderServiceReference.ChangeOrderStatusRequest request) {
            return base.Channel.ChangeOrderStatus(request);
        }
        
        public string ChangeOrderStatus(int orderId, string newStatus) {
            SPC_Web.OrderServiceReference.ChangeOrderStatusRequest inValue = new SPC_Web.OrderServiceReference.ChangeOrderStatusRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.ChangeOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.newStatus = newStatus;
            SPC_Web.OrderServiceReference.ChangeOrderStatusResponse retVal = ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).ChangeOrderStatus(inValue);
            return retVal.Body.ChangeOrderStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.ChangeOrderStatusResponse> SPC_Web.OrderServiceReference.OrderServiceSoap.ChangeOrderStatusAsync(SPC_Web.OrderServiceReference.ChangeOrderStatusRequest request) {
            return base.Channel.ChangeOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.ChangeOrderStatusResponse> ChangeOrderStatusAsync(int orderId, string newStatus) {
            SPC_Web.OrderServiceReference.ChangeOrderStatusRequest inValue = new SPC_Web.OrderServiceReference.ChangeOrderStatusRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.ChangeOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.newStatus = newStatus;
            return ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).ChangeOrderStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.OrderServiceReference.ShowOrdersResponse SPC_Web.OrderServiceReference.OrderServiceSoap.ShowOrders(SPC_Web.OrderServiceReference.ShowOrdersRequest request) {
            return base.Channel.ShowOrders(request);
        }
        
        public string ShowOrders() {
            SPC_Web.OrderServiceReference.ShowOrdersRequest inValue = new SPC_Web.OrderServiceReference.ShowOrdersRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.ShowOrdersRequestBody();
            SPC_Web.OrderServiceReference.ShowOrdersResponse retVal = ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).ShowOrders(inValue);
            return retVal.Body.ShowOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.ShowOrdersResponse> SPC_Web.OrderServiceReference.OrderServiceSoap.ShowOrdersAsync(SPC_Web.OrderServiceReference.ShowOrdersRequest request) {
            return base.Channel.ShowOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.ShowOrdersResponse> ShowOrdersAsync() {
            SPC_Web.OrderServiceReference.ShowOrdersRequest inValue = new SPC_Web.OrderServiceReference.ShowOrdersRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.ShowOrdersRequestBody();
            return ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).ShowOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.OrderServiceReference.SearchOrdersResponse SPC_Web.OrderServiceReference.OrderServiceSoap.SearchOrders(SPC_Web.OrderServiceReference.SearchOrdersRequest request) {
            return base.Channel.SearchOrders(request);
        }
        
        public string SearchOrders(string searchTerm) {
            SPC_Web.OrderServiceReference.SearchOrdersRequest inValue = new SPC_Web.OrderServiceReference.SearchOrdersRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.SearchOrdersRequestBody();
            inValue.Body.searchTerm = searchTerm;
            SPC_Web.OrderServiceReference.SearchOrdersResponse retVal = ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).SearchOrders(inValue);
            return retVal.Body.SearchOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.SearchOrdersResponse> SPC_Web.OrderServiceReference.OrderServiceSoap.SearchOrdersAsync(SPC_Web.OrderServiceReference.SearchOrdersRequest request) {
            return base.Channel.SearchOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.OrderServiceReference.SearchOrdersResponse> SearchOrdersAsync(string searchTerm) {
            SPC_Web.OrderServiceReference.SearchOrdersRequest inValue = new SPC_Web.OrderServiceReference.SearchOrdersRequest();
            inValue.Body = new SPC_Web.OrderServiceReference.SearchOrdersRequestBody();
            inValue.Body.searchTerm = searchTerm;
            return ((SPC_Web.OrderServiceReference.OrderServiceSoap)(this)).SearchOrdersAsync(inValue);
        }
    }
}
