//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Web.ManufacturingPlantServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap")]
    public interface ManufacturingPlantServiceSoap {
        
        // CODEGEN: Generating message contract since element name plantName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddManufacturingPlant", ReplyAction="*")]
        SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantResponse AddManufacturingPlant(SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddManufacturingPlant", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantResponse> AddManufacturingPlantAsync(SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequest request);
        
        // CODEGEN: Generating message contract since element name plantName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditManufacturingPlant", ReplyAction="*")]
        SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantResponse EditManufacturingPlant(SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditManufacturingPlant", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantResponse> EditManufacturingPlantAsync(SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteManufacturingPlantResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteManufacturingPlant", ReplyAction="*")]
        SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantResponse DeleteManufacturingPlant(SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteManufacturingPlant", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantResponse> DeleteManufacturingPlantAsync(SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequest request);
        
        // CODEGEN: Generating message contract since element name ShowManufacturingPlantsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowManufacturingPlants", ReplyAction="*")]
        SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsResponse ShowManufacturingPlants(SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowManufacturingPlants", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsResponse> ShowManufacturingPlantsAsync(SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequest request);
        
        // CODEGEN: Generating message contract since element name plantName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchManufacturingPlant", ReplyAction="*")]
        SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantResponse SearchManufacturingPlant(SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchManufacturingPlant", ReplyAction="*")]
        System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantResponse> SearchManufacturingPlantAsync(SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddManufacturingPlantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddManufacturingPlant", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequestBody Body;
        
        public AddManufacturingPlantRequest() {
        }
        
        public AddManufacturingPlantRequest(SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddManufacturingPlantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string plantName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contactName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phoneNumber;
        
        public AddManufacturingPlantRequestBody() {
        }
        
        public AddManufacturingPlantRequestBody(string plantName, string location, string contactName, string phoneNumber) {
            this.plantName = plantName;
            this.location = location;
            this.contactName = contactName;
            this.phoneNumber = phoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddManufacturingPlantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddManufacturingPlantResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantResponseBody Body;
        
        public AddManufacturingPlantResponse() {
        }
        
        public AddManufacturingPlantResponse(SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddManufacturingPlantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddManufacturingPlantResult;
        
        public AddManufacturingPlantResponseBody() {
        }
        
        public AddManufacturingPlantResponseBody(string AddManufacturingPlantResult) {
            this.AddManufacturingPlantResult = AddManufacturingPlantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditManufacturingPlantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditManufacturingPlant", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequestBody Body;
        
        public EditManufacturingPlantRequest() {
        }
        
        public EditManufacturingPlantRequest(SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditManufacturingPlantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int plantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string plantName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contactName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phoneNumber;
        
        public EditManufacturingPlantRequestBody() {
        }
        
        public EditManufacturingPlantRequestBody(int plantId, string plantName, string location, string contactName, string phoneNumber) {
            this.plantId = plantId;
            this.plantName = plantName;
            this.location = location;
            this.contactName = contactName;
            this.phoneNumber = phoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditManufacturingPlantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditManufacturingPlantResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantResponseBody Body;
        
        public EditManufacturingPlantResponse() {
        }
        
        public EditManufacturingPlantResponse(SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditManufacturingPlantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditManufacturingPlantResult;
        
        public EditManufacturingPlantResponseBody() {
        }
        
        public EditManufacturingPlantResponseBody(string EditManufacturingPlantResult) {
            this.EditManufacturingPlantResult = EditManufacturingPlantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteManufacturingPlantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteManufacturingPlant", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequestBody Body;
        
        public DeleteManufacturingPlantRequest() {
        }
        
        public DeleteManufacturingPlantRequest(SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteManufacturingPlantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int plantId;
        
        public DeleteManufacturingPlantRequestBody() {
        }
        
        public DeleteManufacturingPlantRequestBody(int plantId) {
            this.plantId = plantId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteManufacturingPlantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteManufacturingPlantResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantResponseBody Body;
        
        public DeleteManufacturingPlantResponse() {
        }
        
        public DeleteManufacturingPlantResponse(SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteManufacturingPlantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteManufacturingPlantResult;
        
        public DeleteManufacturingPlantResponseBody() {
        }
        
        public DeleteManufacturingPlantResponseBody(string DeleteManufacturingPlantResult) {
            this.DeleteManufacturingPlantResult = DeleteManufacturingPlantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowManufacturingPlantsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowManufacturingPlants", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequestBody Body;
        
        public ShowManufacturingPlantsRequest() {
        }
        
        public ShowManufacturingPlantsRequest(SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowManufacturingPlantsRequestBody {
        
        public ShowManufacturingPlantsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowManufacturingPlantsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowManufacturingPlantsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsResponseBody Body;
        
        public ShowManufacturingPlantsResponse() {
        }
        
        public ShowManufacturingPlantsResponse(SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowManufacturingPlantsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowManufacturingPlantsResult;
        
        public ShowManufacturingPlantsResponseBody() {
        }
        
        public ShowManufacturingPlantsResponseBody(string ShowManufacturingPlantsResult) {
            this.ShowManufacturingPlantsResult = ShowManufacturingPlantsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchManufacturingPlantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchManufacturingPlant", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequestBody Body;
        
        public SearchManufacturingPlantRequest() {
        }
        
        public SearchManufacturingPlantRequest(SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchManufacturingPlantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> plantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string plantName;
        
        public SearchManufacturingPlantRequestBody() {
        }
        
        public SearchManufacturingPlantRequestBody(System.Nullable<int> plantId, string plantName) {
            this.plantId = plantId;
            this.plantName = plantName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchManufacturingPlantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchManufacturingPlantResponse", Namespace="http://tempuri.org/", Order=0)]
        public SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantResponseBody Body;
        
        public SearchManufacturingPlantResponse() {
        }
        
        public SearchManufacturingPlantResponse(SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchManufacturingPlantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchManufacturingPlantResult;
        
        public SearchManufacturingPlantResponseBody() {
        }
        
        public SearchManufacturingPlantResponseBody(string SearchManufacturingPlantResult) {
            this.SearchManufacturingPlantResult = SearchManufacturingPlantResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManufacturingPlantServiceSoapChannel : SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManufacturingPlantServiceSoapClient : System.ServiceModel.ClientBase<SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap>, SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap {
        
        public ManufacturingPlantServiceSoapClient() {
        }
        
        public ManufacturingPlantServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManufacturingPlantServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturingPlantServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturingPlantServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantResponse SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap.AddManufacturingPlant(SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequest request) {
            return base.Channel.AddManufacturingPlant(request);
        }
        
        public string AddManufacturingPlant(string plantName, string location, string contactName, string phoneNumber) {
            SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequest inValue = new SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequest();
            inValue.Body = new SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequestBody();
            inValue.Body.plantName = plantName;
            inValue.Body.location = location;
            inValue.Body.contactName = contactName;
            inValue.Body.phoneNumber = phoneNumber;
            SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantResponse retVal = ((SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap)(this)).AddManufacturingPlant(inValue);
            return retVal.Body.AddManufacturingPlantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantResponse> SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap.AddManufacturingPlantAsync(SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequest request) {
            return base.Channel.AddManufacturingPlantAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantResponse> AddManufacturingPlantAsync(string plantName, string location, string contactName, string phoneNumber) {
            SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequest inValue = new SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequest();
            inValue.Body = new SPC_Web.ManufacturingPlantServiceReference.AddManufacturingPlantRequestBody();
            inValue.Body.plantName = plantName;
            inValue.Body.location = location;
            inValue.Body.contactName = contactName;
            inValue.Body.phoneNumber = phoneNumber;
            return ((SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap)(this)).AddManufacturingPlantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantResponse SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap.EditManufacturingPlant(SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequest request) {
            return base.Channel.EditManufacturingPlant(request);
        }
        
        public string EditManufacturingPlant(int plantId, string plantName, string location, string contactName, string phoneNumber) {
            SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequest inValue = new SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequest();
            inValue.Body = new SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequestBody();
            inValue.Body.plantId = plantId;
            inValue.Body.plantName = plantName;
            inValue.Body.location = location;
            inValue.Body.contactName = contactName;
            inValue.Body.phoneNumber = phoneNumber;
            SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantResponse retVal = ((SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap)(this)).EditManufacturingPlant(inValue);
            return retVal.Body.EditManufacturingPlantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantResponse> SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap.EditManufacturingPlantAsync(SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequest request) {
            return base.Channel.EditManufacturingPlantAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantResponse> EditManufacturingPlantAsync(int plantId, string plantName, string location, string contactName, string phoneNumber) {
            SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequest inValue = new SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequest();
            inValue.Body = new SPC_Web.ManufacturingPlantServiceReference.EditManufacturingPlantRequestBody();
            inValue.Body.plantId = plantId;
            inValue.Body.plantName = plantName;
            inValue.Body.location = location;
            inValue.Body.contactName = contactName;
            inValue.Body.phoneNumber = phoneNumber;
            return ((SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap)(this)).EditManufacturingPlantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantResponse SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap.DeleteManufacturingPlant(SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequest request) {
            return base.Channel.DeleteManufacturingPlant(request);
        }
        
        public string DeleteManufacturingPlant(int plantId) {
            SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequest inValue = new SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequest();
            inValue.Body = new SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequestBody();
            inValue.Body.plantId = plantId;
            SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantResponse retVal = ((SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap)(this)).DeleteManufacturingPlant(inValue);
            return retVal.Body.DeleteManufacturingPlantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantResponse> SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap.DeleteManufacturingPlantAsync(SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequest request) {
            return base.Channel.DeleteManufacturingPlantAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantResponse> DeleteManufacturingPlantAsync(int plantId) {
            SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequest inValue = new SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequest();
            inValue.Body = new SPC_Web.ManufacturingPlantServiceReference.DeleteManufacturingPlantRequestBody();
            inValue.Body.plantId = plantId;
            return ((SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap)(this)).DeleteManufacturingPlantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsResponse SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap.ShowManufacturingPlants(SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequest request) {
            return base.Channel.ShowManufacturingPlants(request);
        }
        
        public string ShowManufacturingPlants() {
            SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequest inValue = new SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequest();
            inValue.Body = new SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequestBody();
            SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsResponse retVal = ((SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap)(this)).ShowManufacturingPlants(inValue);
            return retVal.Body.ShowManufacturingPlantsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsResponse> SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap.ShowManufacturingPlantsAsync(SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequest request) {
            return base.Channel.ShowManufacturingPlantsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsResponse> ShowManufacturingPlantsAsync() {
            SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequest inValue = new SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequest();
            inValue.Body = new SPC_Web.ManufacturingPlantServiceReference.ShowManufacturingPlantsRequestBody();
            return ((SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap)(this)).ShowManufacturingPlantsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantResponse SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap.SearchManufacturingPlant(SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequest request) {
            return base.Channel.SearchManufacturingPlant(request);
        }
        
        public string SearchManufacturingPlant(System.Nullable<int> plantId, string plantName) {
            SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequest inValue = new SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequest();
            inValue.Body = new SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequestBody();
            inValue.Body.plantId = plantId;
            inValue.Body.plantName = plantName;
            SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantResponse retVal = ((SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap)(this)).SearchManufacturingPlant(inValue);
            return retVal.Body.SearchManufacturingPlantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantResponse> SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap.SearchManufacturingPlantAsync(SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequest request) {
            return base.Channel.SearchManufacturingPlantAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantResponse> SearchManufacturingPlantAsync(System.Nullable<int> plantId, string plantName) {
            SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequest inValue = new SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequest();
            inValue.Body = new SPC_Web.ManufacturingPlantServiceReference.SearchManufacturingPlantRequestBody();
            inValue.Body.plantId = plantId;
            inValue.Body.plantName = plantName;
            return ((SPC_Web.ManufacturingPlantServiceReference.ManufacturingPlantServiceSoap)(this)).SearchManufacturingPlantAsync(inValue);
        }
    }
}
